### ISSUE TITLE
Mesh object not clean up upon exit.

### ISSUE THREAD

**Issue by vutle** [xamarin/urho#102]
Hi, after we run the below code the first time. On subsequence run, if we are using a different Box.mdl mesh file, the render does not update this mesh, it still uses the previous cache mesh file.

 ResourceCache cache = ResourceCache;
 Node node  = scene.CreateChild(name);
 var obj = node.CreateComponent<StaticModel>();
 obj.Model = cache.GetModel("Models/Box.mdl");
 obj.CastShadows = false;

**Comment by EgorBo** [comment]
@vutle you mean you changed Box.mdl to another 3d object while the app was running and you expected that next call of GetModel("Models/Box.mdl") will give you a new model? It's called Resource**Cache** - it caches :-)

**Comment by vutle** [comment]
Yup, I know what it is. Since I used C++ Urho3D. The C++ version works fine when I did that. 
No, I stopped the model and rerun again with a different "Box.mdl" file.
I also tried to release all resource for ResourceCach. But that also doesn't help.
Cheers

**Comment by vutle** [comment]
Hi, I found out that the engine load CoreData.pak file at start up. I suspect it contains basic 3D object included Box.mdl. Is it possible if we don't load any model object in this file?

By the way I try to unpack the file. But can't on my machine. Did you guys put encryption on it or something?

**Comment by EgorBo** [comment]
@vutle You can disable CoreData loading via ApplicationOptions (ResourcePath afair) and provide a path to your custom pak or directory. Also please check AutoLoad parameter.
CoreData.pak is created via PackageTool.exe (Urho3D built-in): https://github.com/xamarin/urho/blob/master/MakeWindows#L23

**Comment by EgorBo** [comment]
Closed by the previous comment actually.
