### ISSUE TITLE
System.InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by vrivotti** [xamarin/urho#103]
Sometimes I get this exception on startup:

04-13 13:49:57.461 E/mono    (16814): 
04-13 13:49:57.461 E/mono    (16814): Unhandled Exception:
04-13 13:49:57.461 E/mono    (16814): System.InvalidCastException: Specified cast is not valid.
04-13 13:49:57.461 E/mono    (16814):   at System.Reflection.IntrospectionExtensions.GetTypeInfo (System.Type type) [0x00017] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/reflection/introspectionextensions.cs:29 
04-13 13:49:57.461 E/mono    (16814):   at Urho.Application.CreateInstance (System.Type applicationType, Urho.ApplicationOptions options) [0x00000] in <filename unknown>:0 
04-13 13:49:57.461 E/mono    (16814):   at Urho.Droid.UrhoSurface+<>c__DisplayClass3_0.<CreateSurface>b__0 (IntPtr contextPtr) [0x00000] in <filename unknown>:0 
04-13 13:49:57.461 E/mono-rt (16814): [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidCastException: Specified cast is not valid.
04-13 13:49:57.461 E/mono-rt (16814):   at System.Reflection.IntrospectionExtensions.GetTypeInfo (System.Type type) [0x00017] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/reflection/introspectionextensions.cs:29 
04-13 13:49:57.461 E/mono-rt (16814):   at Urho.Application.CreateInstance (System.Type applicationType, Urho.ApplicationOptions options) [0x00000] in <filename unknown>:0 
04-13 13:49:57.461 E/mono-rt (16814):   at Urho.Droid.UrhoSurface+<>c__DisplayClass3_0.<CreateSurface>b__0 (IntPtr contextPtr) [0x00000] in <filename unknown>:0

**Comment by vrivotti** [comment]
A more complete stack trace:

04-13 17:34:40.141 E/mono    (14376): 
04-13 17:34:40.141 E/mono    (14376): Unhandled Exception:
04-13 17:34:40.141 E/mono    (14376): System.InvalidCastException: Specified cast is not valid.
04-13 17:34:40.141 E/mono    (14376):   at System.Reflection.IntrospectionExtensions.GetTypeInfo (System.Type type) [0x00017] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/reflection/introspectionextensions.cs:29 
04-13 17:34:40.141 E/mono    (14376):   at Urho.Application.CreateInstance (System.Type applicationType, Urho.ApplicationOptions options) [0x00000] in <filename unknown>:0 
04-13 17:34:40.141 E/mono    (14376):   at Urho.Droid.UrhoSurface+<>c__DisplayClass3_0.<CreateSurface>b__0 (IntPtr contextPtr) [0x00000] in <filename unknown>:0 
04-13 17:34:40.141 E/mono-rt (14376): [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidCastException: Specified cast is not valid.
04-13 17:34:40.141 E/mono-rt (14376):   at System.Reflection.IntrospectionExtensions.GetTypeInfo (System.Type type) [0x00017] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/reflection/introspectionextensions.cs:29 
04-13 17:34:40.141 E/mono-rt (14376):   at Urho.Application.CreateInstance (System.Type applicationType, Urho.ApplicationOptions options) [0x00000] in <filename unknown>:0 
04-13 17:34:40.141 E/mono-rt (14376):   at Urho.Droid.UrhoSurface+<>c__DisplayClass3_0.<CreateSurface>b__0 (IntPtr contextPtr) [0x00000] in <filename unknown>:0 
04-13 17:34:40.241 D/ViewRootImpl(14376): MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
04-13 17:34:40.361 E/libEGL  (14376): eglMakeCurrent:1056 error 3001 (EGL_NOT_INITIALIZED)
04-13 17:34:40.361 F/OpenGLRenderer(14376): Failed to make current on surface 0x7f86aa7480, error=EGL_NOT_INITIALIZED
04-13 17:34:40.361 F/libc    (14376): Fatal signal 6 (SIGABRT), code -6 in tid 14476 (RenderThread)

**Comment by vrivotti** [comment]
Maybe the problem is related to this:

**Comment by EgorBo** [comment]
It was a kind of race condition as far as I remember, fixed a long time ago.
