### ISSUE TITLE
Save image

### ISSUE THREAD

**Issue by tiago156** [xamarin/urho#106]
Hi,

is there a way to encode a Texture2D as image? I'm trying to get a image from the render surface, it there any alternative? Should I better use some capture screen functionality?

```
Viewport viewport = new Viewport(Context, scene, camera, null);
renderTexture = new Texture2D();
renderTexture.SetSize(1024, 768, Graphics.RGBFormat, TextureUsage.Rendertarget);
renderTexture.FilterMode = TextureFilterMode.Bilinear;
RenderSurface surface = renderTexture.RenderSurface;
surface.SetViewport(0, viewport);
```

Thanks

**Comment by manuelcosta74** [comment]
Texture2D themeTexture;
IntPtr ptr = pointer to our cpu data buffer
themeTexture.GetData(0, ptr);

@tiago156 , @EgorBo introduced it in https://www.nuget.org/packages/UrhoSharp/1.0.454-beta

**Comment by tiago156** [comment]
Thanks
