### ISSUE TITLE
Wpf questions

### ISSUE THREAD

**Issue by tiago156** [xamarin/urho#107]
Hi,

I have two questions regarding the use of UrhoSharp in Wpf:

1-Is there a way to detach the Urho update loop to the Wpf ui thread (putting a Thread.sleep on OnUpdate method makes Wpf UI sleeps as well)?

2-Is there a way to avoid using the WindowFormsHost on WPF? Currently we dont need a high FPS count, so we could sacrifice the FPS count to avoid using this control. Maybe some memory rendering, or render to wpf image control.

Thanks.

**Comment by EgorBo** [comment]
@tiago156 it's possible but it will require a lot of work in Urho3D, SDL and the bindings.
Something similar is done for UWP - it doesn't use WindowFormsHost and it doesn't use main thread for the main loop.
