### ISSUE TITLE
UrhoSharp.Forms support for UWP?

### ISSUE THREAD

**Issue by JimSEOW** [xamarin/urho#109]
First, this project is amazing! Within a short time, new sample for UWP has been shared. Could you please share with us when the Xamarin.Forms (UrhoSharp.Forms with uap10) will be [supported](https://github.com/xamarin/urho-samples/tree/744c26b6a7dd95f0238d682f2b8a7935e775fcda/FormsSample). 
 Thanks and such a great job!

**Comment by JimSEOW** [comment]
https://www.nuget.org/packages/UrhoSharp.Forms/
UrhoSharp for Xamarin.Forms 1.0.500
Release Notes
## Features:
PREVIEW: UWP support (x86 only) see samples here.
DirectX11 renderer (UWP and optional for Windows)

The current 1.0.500 "UrhoSharp.Forms" does not support UWP yet. 
There is no uap10 folder in the distirubted Nuget package for  Xamarin.Forms 1.0.500

**Comment by EgorBo** [comment]
@JimSEOW will be available in upcoming release.

**Comment by JimSEOW** [comment]
Thanks, that will be great!

I notice that SkiaSharp uses one DLL for both UWP native and Xamarin.Forms (UWP). There is no need to have SkiaSharp.Forms.dll

Could this be done in UrhoSharp?  

FYI: The availability of WinForm UrhoSharp samples really helps. It is faster to compile WinForm than UWP in my hands..

**Comment by JimSEOW** [comment]
HI @EgorBo excited of your latest 1.0.557. Is this release support UrhoSharp.Forms for UWP? Great job, lots of bug fix. Moving fast.

**Comment by EgorBo** [comment]
@JimSEOW Unfortunately not yet, with the next update but it still doesn't support ARM so you won't be able to run it in W10 Mobile.

**Comment by JimSEOW** [comment]
@EgorBo What is limiting this? could I lobby this through the Urho3D to put more community support for W10 Mobile? UrhoSharp is really cool. Because of lack of W10 Mobile support, I have to use Droid instead of W10 Mobile for doing a demo. 

FYI: If you could release a UrhoSharp.Forms version that works with x86, it still helps the development works at my laptop before moving to Droid. **ONLY when this is part of your schedule**

**Comment by EgorBo** [comment]
>>could I lobby this through the Urho3D to put more community support for W10 Mobile? 
Urho3D doesn't support UWP out of the box, that was our initiative. I'll try to add ARM support once I finish tasks with higher priority.

**Comment by EgorBo** [comment]
@JimSEOW Xamarin.Forms UWP is in the master, will be available in with the next update. I close this issue and create a new one with ARM support for UrhoSharp.UWP

**Comment by kj4bix** [comment]
Is this saying that Urho3D will work with UWP x86 devices? I need my app to run on Windows 10 tablets don't really care about mobile devices.

Thanks
Alan Anderson

**Comment by EgorBo** [comment]
@kj4bix yes. it will.
