### ISSUE TITLE
How to build UrhoSharp in Window?

### ISSUE THREAD

**Issue by JimSEOW** [xamarin/urho#113]
I have read your excellent presentation: (C++ via C#) http://www.slideshare.net/egorbogatov/c-via-c
It is an amazing how you have made UrhoSharp porting from Urho3D looks simple. 
It will be educational for us if you could also consider showing us how to do it ALL in Windows. 

1. Install:
2. Clone the repository including submodules
3. Compile Urho.pch
4. Generate C# bindings from Urho.pch
8. Compile UrhoSharp for Windows (64 bit)

With SkiaSharp, I could build all in WIndow and this allows me to keep up with the latest samples and shared recipes to be used in SkiaSharp.

Urho3D community is many times more active. New codes appear very frequently. Having a workflow to build UrhoSharp ALL in Windows allow us to integrate the latest features to our work. 

Perhaps, this could also help to grow UrhoSharp community pioneered by Xamarin.

This could be relevant especailly some of us really would like to see how to use UrhoSharp directly (Eventually) to develop Hololens App in UWP.

**Comment by EgorBo** [comment]
@JimSEOW unfortunately it's not possible at this moment since some of the Binder's clang-related dependencies support only OS X.

**Comment by JimSEOW** [comment]
`#compile Urho.pch for SharpieBinder on Mac

PchMac: $(LOCAL_CLANG)
	if test ! -e /usr/include; then xcode-select --install; fi
	make -j1 Urho3D_Mac -f MakeMac && $(CUSTOM_CLANG) -cc1 -emit-pch -DURHO3D_OPENGL -o Bindings/Urho.pch Bindings/Native/all-urho.cpp  -IUrho3D/Urho3D_Mac/include -IUrho3D/Urho3D_Mac/include/Urho3D/ThirdParty`

`LOCAL_CLANG=clang+llvm-3.7.0-x86_64-apple-darwin/bin/clang

CUSTOM_CLANG=`pwd`/$(LOCAL_CLANG)`

`3. Compile Urho.pch

The following command will download Clang 3.7.0 if you do not have it installed, and use this to scan the Urho header files:

make PchMac`


HI EgorBo, I have not figure out all the necessary pieces.  it seems that both LOCAL_CLANG and CUSTOM_CLANG can be installed in WIndows.
The instruction to scan Urho Header files are performed by the binary CLANG in Windows.

I continue the discussion here perhaps someone with more knowledge could make this happens in Window.

Alternatively, could you provide a zip files of the extracted C# files needed to run SharpieBinder project , so that some of us could continue to experiment on how to get the Window CLANG to extract the c# files close to what you can generate.

Perhaps there are still more (Mac unique) steps which I am not aware. 

Otherwise, we probably have to end-up getting a used Mac Pro soon from Ebay :-(  to continue our Xamarin learning experience. .

**Comment by migueldeicaza** [comment]
Currently we need the Mac, it is unfortunate, but the amount of work that we need to put into bringing the dependency tools to build natively on Windows is just too high.

**Comment by JimSEOW** [comment]
HI migueldeicaza, congratulate your team for pioneering many new grounds. 
Through learning Xamarin, I found out that there are many new exciting technologies that your team has developed that is making "BiG" impact for the C# ecosystem. Through the SharpBinding example shown in UrhoSharp, c# port no longer needs to be lagging behind the latest c++ codes in Urho3D. Which is the case for Mogre since many many years.

**Comment by CalicoBay** [comment]
Hi you guys, I have time to put into Windows. True cross-platform should include UWP. Just send me in the right direction and I'll go. Otherwise I'll probably dump iPhone and Android and just develop for UWP with C++. I'm really interested in Xamarin et al and believe I possess the skills. At this stage of my career I'm more interested in process than revenue. I wrote my first program in 1969.
