### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by tiago156** [xamarin/urho#114]
I could not find a method to take a screenshot, how can I do it?

Thanks,

**Comment by EgorBo** [comment]
oh it seems Graphics::TakeScreenshot is not surfaced to C#. Will be added.

**Comment by EgorBo** [comment]
Added.

**Comment by Therzok** [comment]
For reference: https://github.com/xamarin/urho/commit/49acf9a696c338852b5de2d7d73e4f64321fa74c
