### ISSUE TITLE
Reading MDL Vertices/Triangles

### ISSUE THREAD

**Issue by paulohumberto42** [xamarin/urho#124]
Is there a way for me to read the Model vertices/triangles in runtime?

**Comment by EgorBo** [comment]
@paulohumberto42 yes there is, take a look at this sample: https://github.com/xamarin/urho-samples/blob/09ed99f3a9389f131ed6a0fdadae26a929ee7b6f/FeatureSamples/Core/34_DynamicGeometry/DynamicGeometry.cs#L137-L138
