### ISSUE TITLE
Compliling on windows without OSX, or win32 version of DLL

### ISSUE THREAD

**Issue by gattila** [xamarin/urho#125]
Hi!

I need a win32 version of the dll. I read the documentation to find out how to compile it on windows, but  as I read, it is not possible without OS X environment due to SharpieBinder.

Unfortunately, I don't have OSX or any Apple computer. Is there any way to make possible compiling UhroSharp without OSX, or provide win32 version of the dlls anyhow ?

**Comment by gattila** [comment]
Fortunately the win32 version is supported in the official package.

**Comment by EgorBo** [comment]
@gattila yep, you just need to rename it from mono-urho32.dll to mono-urho.dll
