### ISSUE TITLE
Missing class Urho.UrhoEngine

### ISSUE THREAD

**Issue by wwiz** [xamarin/urho#126]
In Urho.Engine class documentation there is a statement that "Before a Urho3D application can enter its main loop, the Engine subsystem object must be created and initialized by calling the **Urho.UrhoEngine.Initialize** method."
The thing is, that mentioned class doesn't exist so it seems that currently it is not possible to have any control when **Engine.RunFrame**() method is called. It would be great to have it under full control.

**Comment by EgorBo** [comment]
@wwiz, sorry I forgot to update the Doc, UrhoEngine was removed. But what do you mean by "currently it is not possible to have any control when Engine.RunFrame() method is called"? what do you expect to control?

**Comment by wwiz** [comment]
Hi. I would like to control when the frame is to be rendered, but perhaps I am just thinking incorrectly, or perhaps I am trying to misuse Urho.
In general I would like to use Urho in some tool (not game) in which I want to implement 3d preview. In this tool 3d picture is quite static except situations where user is actively modifying that, which happens perhaps 10% of time when view is presented. 
In native Urho3D Application::Run() is doing something like:
        **while (!engine_->IsExiting())
            engine_->RunFrame();**
which means, that if I would use native library I could probably ignore Application::Run() and I could implement my own procedure which runs "RunFrame" only when it is really needed, that is when I have anything to be updated on 3d view. I wanted to experiment with that idea using UrhoSharp, but as it seems that I cannot initialize Engine separately, I cannot also avoid default loop **while (...) engine.RunFrame()** which seems to be just waste of resources in my scenario.
I thought that it would be good idea to reduce battery consumption. I tried to experiment a bit with MaxFps settings, but I found that setting it to small value causes reduction of whole app responsiveness and in general I wasn't really happy with results.

Sorry if my ideas or doubts contains any fundamental mistake - I am just building my knowledge and experience in the new area so that I can easily miss something obvious for people with bigger knowledge.

**Comment by EgorBo** [comment]
@wwiz you can use UrhoSurface.Pause/Resume on iOS - it pauses/resumes renderer. But yeah I guess it needs some customization.

**Comment by wwiz** [comment]
Thanks for the hint :) and thanks for marking this issue as enhacement :)

**Comment by EgorBo** [comment]
I added a parameter to Application::Run(bool autorun)
in case of false it won't start update/render loop and you can control it yourself by
for example:
```
var app = new MyApp();
app.Run(false);
for (int i=0; i<5; i++)
{
app.Engine.RunFrame();
//sleep here for desired FPS
}
```

this will render only 5 frames
