### ISSUE TITLE
Exception when FormsAppCompatActivity is used.

### ISSUE THREAD

**Issue by mjeronimoa** [xamarin/urho#128]
Hi,
It seems to be that the framework is incompatible with the use of FormsAppCompatActivity(needed if you want to use some UI controls of the Android Support Library).
Exception "System.InvalidOperationException: Platform implementation is not referenced" is raised when trying to run the OnAppearing() method of the xamarin forms sample.
SanderSchutten seems to have had the same problem according to this topic https://forums.xamarin.com/discussion/67735/android-renderers-timing-issue-when-using-masterdetailpage-with-formsappcompatactivity and he created a sample project.

**Comment by EgorBo** [comment]
"Platform implementation is not referenced" means more likely that you didn't add UrhoSharp.Forms package to your Android project. Urho uses Bait and Switch approach.

**Comment by mjeronimoa** [comment]
@EgorBo I do have installed UrhoSharp.Forms and Xamarin.Forms packages as it is in the sample project.

**Comment by EgorBo** [comment]
@mjeronimoa I see. I'll take a look at the sample.

**Comment by mjeronimoa** [comment]
@EgorBo Thanks a lot. Let me know if you need any help for reproducing the error

**Comment by mjeronimoa** [comment]
@EgorBo Any advance with it?have you eben able to reproduce it?

**Comment by mahlm** [comment]
I'm having the same error on iOS - UrhoSharp.Forms and Xamarin.Forms are referenced.

```
await _surface.Show<Lab3D> (
    new ApplicationOptions (assetsFolder: null) { 
        Orientation = ApplicationOptions.OrientationType.Portrait 
    }
);
```

I'll do some digging today.

**Comment by mahlm** [comment]
Fixed - i was initializing the UrhoSurface before adding to the ContentPage.  Adding it to the Page before calling show on the surface resolved my problem.  I'll just need to hide the containing view first.

**Comment by mjeronimoa** [comment]
@mahlm @EgorBo Now I'm really confused. After updating my laptop to Windows 10 and installing and unistalling visual studio, everything seems to be working fine.
Any idea about what it can be related with?

**Comment by migueldeicaza** [comment]
Closing per last message.
