### ISSUE TITLE
Matrix3x4 missing bindings

### ISSUE THREAD

**Issue by elios264** [xamarin/urho#132]
Missing all native methods , I needed the inverse method from the camera

**Comment by EgorBo** [comment]
@elios264 it has Inverse https://github.com/xamarin/urho/blob/9e6a810ecffed19e868f1ef0f4f7cbbb037e5205/Bindings/Portable/Structs.cs#L271 but I am not sure if it's available via the latest nuget (probably not).

**Comment by elios264** [comment]
Yes!, you are right, sorry I didn't check the source master branch first, so how often do you release the nuget packages, ( i do not own a mac  u_u )

**Comment by migueldeicaza** [comment]
Mhm, we should look into publishing packages straight from our internal CI.

@duncanmak ^^

**Comment by migueldeicaza** [comment]
added the BoundingBox methods.
