### ISSUE TITLE
Crash in Application.Run when setting model on StaticModel before adding component to the Node

### ISSUE THREAD

**Issue by elios264** [xamarin/urho#133]
Using  1.0.557,  adding this node to the Scene recreates the crash:

	public class SampleCustomGeometry : Node
	{

		public SampleCustomGeometry()
		{
			const uint numVertices = 18;
			float[] vertexData =
			{
				// Position             Normal
				0.0f, 0.5f, 0.0f, 0.0f, 0.0f, 0.0f,
				0.5f, -0.5f, 0.5f, 0.0f, 0.0f, 0.0f,
				0.5f, -0.5f, -0.5f, 0.0f, 0.0f, 0.0f,

				0.0f, 0.5f, 0.0f, 0.0f, 0.0f, 0.0f,
				-0.5f, -0.5f, 0.5f, 0.0f, 0.0f, 0.0f,
				0.5f, -0.5f, 0.5f, 0.0f, 0.0f, 0.0f,

				0.0f, 0.5f, 0.0f, 0.0f, 0.0f, 0.0f,
				-0.5f, -0.5f, -0.5f, 0.0f, 0.0f, 0.0f,
				-0.5f, -0.5f, 0.5f, 0.0f, 0.0f, 0.0f,

				0.0f, 0.5f, 0.0f, 0.0f, 0.0f, 0.0f,
				0.5f, -0.5f, -0.5f, 0.0f, 0.0f, 0.0f,
				-0.5f, -0.5f, -0.5f, 0.0f, 0.0f, 0.0f,

				0.5f, -0.5f, -0.5f, 0.0f, 0.0f, 0.0f,
				0.5f, -0.5f, 0.5f, 0.0f, 0.0f, 0.0f,
				-0.5f, -0.5f, 0.5f, 0.0f, 0.0f, 0.0f,

				0.5f, -0.5f, -0.5f, 0.0f, 0.0f, 0.0f,
				-0.5f, -0.5f, 0.5f, 0.0f, 0.0f, 0.0f,
				-0.5f, -0.5f, -0.5f, 0.0f, 0.0f, 0.0f
			};

			short[] indexData =
			{
				0, 1, 2,
				3, 4, 5,
				6, 7, 8,
				9, 10, 11,
				12, 13, 14,
				15, 16, 17
			};

			Model fromScratchModel = new Model();
			VertexBuffer vb = new VertexBuffer(Context, false);
			IndexBuffer ib = new IndexBuffer(Context, false);
			Geometry geom = new Geometry();

			vb.Shadowed = false;

			vb.SetSize(numVertices, ElementMask.Position | ElementMask.Normal, false);
			vb.SetData(vertexData);

			ib.Shadowed = true;
			ib.SetSize(numVertices, false, false);
			ib.SetData(indexData);

			geom.SetVertexBuffer(0, vb);
			geom.IndexBuffer = ib;
			geom.SetDrawRange(PrimitiveType.TriangleList, 0, numVertices, false);

			fromScratchModel.NumGeometries = 1;
			fromScratchModel.SetGeometry(0, 0, geom);
			fromScratchModel.BoundingBox = new BoundingBox(new Vector3(-0.5f, -0.5f, -0.5f), new Vector3(0.5f, 0.5f, 0.5f));

			var model = new StaticModel(Context);
			model.Model = fromScratchModel;
			AddComponent(model);
			//model.Model = fromScratchModel;
		}
	}

If the last line is uncommented and the 3rd from the bottom commented the app will stop crashing.

**Comment by EgorBo** [comment]
@elios264 known issue, I'd recommend to create components via CreateComponent method:
```
var model = node.CreateComponent<StaticModel>();
model.Model =
```
PS: why do you subclass Node instead of Component?

**Comment by elios264** [comment]
because there's no way to avoid the crash with a CustomComponent 

      var testNode = Scene.CreateChild("test");
      testNode.CreateComponent<SampleCustomGeometry>();

    public class SampleCustomGeometry : StaticModel
    {
        public SampleCustomGeometry()
        {
            /**same previous code**/
            Model = /*fromScratchModel*/;
        }
    }

Is this a UrhoSharp issue or is it also present in urho3d?

**Comment by EgorBo** [comment]
@elios264 Try to set model in your SampleCustomGeometry in OnNodeSet method (override).

**Comment by migueldeicaza** [comment]
@EgorBo Do you know what is the source of the problem?   When you said that this was a known issue?

**Comment by EgorBo** [comment]
@migueldeicaza Urho3D issue
this C++ code crash:
```
auto mushroomObject = new StaticModel(context_);
mushroomObject->SetModel(cache->GetResource<Model>("Models/Mushroom.mdl"));
mushroomObject->SetMaterial(cache->GetResource<Material>("Materials/Mushroom.xml"));
mushroomNode->AddComponent(mushroomObject, 0, CreateMode::REPLICATED);
```
This doesn't (AddComponent before SetModel)
```
auto mushroomObject = new StaticModel(context_);
mushroomNode->AddComponent(mushroomObject, 0, CreateMode::REPLICATED); 
mushroomObject->SetModel(cache->GetResource<Model>("Models/Mushroom.mdl"));
mushroomObject->SetMaterial(cache->GetResource<Material>("Materials/Mushroom.xml"));
```
This one also works fine:
```
auto mushroomObject = mushroomNode.CreateComponent<StaticModel>(context_);
mushroomObject->SetModel(cache->GetResource<Model>("Models/Mushroom.mdl"));
mushroomObject->SetMaterial(cache->GetResource<Material>("Materials/Mushroom.xml"));
```

**Comment by migueldeicaza** [comment]
Let me suggest we then close this bug, and just link the upstream Urho3D bug to this for now.

**Comment by EgorBo** [comment]
Fixed via https://github.com/urho3d/Urho3D/commit/2f25c3b98dd73767bf598fced875c8e31f172610 as I said - AddComponent instead of CreateComponent<> is a bad idea.
