### ISSUE TITLE
Draw artifacts on MALI400 GPU

### ISSUE THREAD

**Issue by mayatforest** [xamarin/urho#137]
Hi.
We have some troubles on devices with MALI400 graphics (Xamarin+urho).
This GPU have default dithering enabled in back buffers and resulted image  of rendering is drawed with artifacts (tested on static scene from urho examples).

Please see details here http://urho3d.prophpbb.com/topic2212.html

Please add options to call glDisable(GL_DITHER) or may be help with other solution to remove artifacts.

**Comment by EgorBo** [comment]
Anyway I think it should be fixed in the upstream (Urho3D) - **if MALI - turn of dithering** (OGLGraphics.cpp?)

**Comment by mayatforest** [comment]
Thanks, for answer. I added issue in main urho3d upstream https://github.com/urho3d/Urho3D/issues/1489

I tryed your solution with dllimport. But call to glDisable fail to not found method. What may be wrong?

`[Mono] DllImport searching in: 'mono-urho' ('libmono-urho.so').
[Mono] Searching for 'urho_subscribe_KeyDown'.
[Mono] Probing 'urho_subscribe_KeyDown'.
[Mono] Found as 'urho_subscribe_KeyDown'.
[Mono] DllImport attempting to load: 'mono-urho'.
[Mono] DllImport error loading library '/mnt/sdcard/Android/data/com.app/files/.__override__/libmono-urho': 'Cannot load library: load_library[1098]: Library '/data/data/com.app/lib//mnt/sdcard/Android/data/com.app/files/.__override__/libmono-urho' not found'.
[Mono] DllImport loaded library '/mnt/sdcard/Android/data/com.app/files/.__override__/libmono-urho.so'.
[Mono] DllImport searching in: 'mono-urho' ('/mnt/sdcard/Android/data/com.app/files/.__override__/libmono-urho.so').
[Mono] Searching for 'glDisable'.
[Mono] Probing 'glDisable'.
[Mono] Could not find 'glDisable' due to 'Symbol not found: load_library[1098]: Library '/data/data/com.app/lib//mnt/sdcard/Android/data/com.app/files/.__override__/libmono-urho' not found'.
[Mono] Probing 'glDisable'.
[Mono] Could not find 'glDisable' due to 'Symbol not found: load_library[1098]: Library '/data/data/com.app/lib//mnt/sdcard/Android/data/com.app/files/.__override__/libmono-urho' not found'.
[Mono] Probing 'glDisableA'.
[Mono] Could not find 'glDisableA' due to 'Symbol not found: load_library[1098]: Library '/data/data/com.app/lib//mnt/sdcard/Android/data/com.app/files/.__override__/libmono-urho' not found'.
[Mono] Probing 'glDisableA'.
[Mono] Could not find 'glDisableA' due to 'Symbol not found: load_library[1098]: Library '/data/data/com.app/lib//mnt/sdcard/Android/data/com.app/files/.__override__/libmono-urho' not found'.
[Mono] DllImport searching in: 'mono-urho' ('libmono-urho.so').
[Mono] Searching for 'Controls_Create'.
[Mono] Probing 'Controls_Create'.
[Mono] Found as 'Controls_Create'.
[Mono] DllImport searching in: 'mono-urho' ('/mnt/sdcard/Android/data/com.app/files/.__override__/libmono-urho.so').
[Mono] Searching for 'glDisable'.
[Mono] Probing 'glDisable'.
[Mono] Could not find 'glDisable' due to 'Symbol not found: load_library[1098]: Library '/data/data/com.app/lib//mnt/sdcard/Android/data/com.app/files/.__override__/libmono-urho' not found'.
[Mono] Probing 'glDisable'.
[Mono] Could not find 'glDisable' due to 'Symbol not found: load_library[1098]: Library '/data/data/com.app/lib//mnt/sdcard/Android/data/com.app/files/.__override__/libmono-urho' not found'.
[Mono] Probing 'glDisableA'.
[Mono] Could not find 'glDisableA' due to 'Symbol not found: load_library[1098]: Library '/data/data/com.app/lib//mnt/sdcard/Android/data/com.app/files/.__override__/libmono-urho' not found'.
[Mono] Probing 'glDisableA'.
[Mono] Could not find 'glDisableA' due to 'Symbol not found: load_library[1098]: Library '/data/data/com.app/lib//mnt/sdcard/Android/data/com.app/files/.__override__/libmono-urho' not found'.`

**Comment by EgorBo** [comment]
I'll check why it didn't find glDisable however I updated the bindings in master so SetDither is already here (as Dither property)

**Comment by mayatforest** [comment]
Thanks, waiting for dllimport solution. 
Bw when next update to urho package is sheduled?

**Comment by EgorBo** [comment]
@mayatforest regarding Dllimport I forgot to specify callingConvention can you please try again with 
```
[DllImport("mono-urho", CallingConvention = CallingConvention.Cdecl)]
public static extern void glDisable(uint c);
```
or
```
[DllImport("mono-urho", CallingConvention = CallingConvention.StdCall)]
public static extern void glDisable(uint c);
```

**Comment by mayatforest** [comment]
@EgorBo 
Thanks. Dllimport dont help - same error with not found func in lib, that strange.
BW, i fixed with call to Android.Opengl.GLES20.GlDisable(Android.Opengl.GLES20.GlDither);
And this helps to disable artifacts. :))) Thanks for your support. Спасибо ;)
