### ISSUE TITLE
Missing TileMap2D.PositionToTileIndex()

### ISSUE THREAD

**Issue by vans163** [xamarin/urho#138]
I need to convert a user click on a TileMap2D into the x,y tile that was clicked. So far the docs say to use

```
PositionToTileIndex() to convert Urho position to tile index (returns false if position is outside of the map)
```

but PositionToTileIndex is not exposed in UrhoSharp.

Perhaps related http://urho3d.prophpbb.com/topic2211.html, but you can see the long winded solution to do what PositionToTileIndex does.

**Comment by EgorBo** [comment]
@vans163 looks like it was added recently to Urho3D. I'll update the bindings.

**Comment by EgorBo** [comment]
Surfaced.
