### ISSUE TITLE
Please update to master branch of urho3d - fix Graphics.TakeScreenShot

### ISSUE THREAD

**Issue by mayatforest** [xamarin/urho#149]
Hello.
I have not working Graphics.TakeScreenShot in android. It fixed in commit https://github.com/urho3d/Urho3D/commit/a2d86f1a59423256365902cdd14dd2c9f3785f1c of 12.08.2016.

Please update to master branch of urho3d

Thanks.

**Comment by EgorBo** [comment]
In the master.
