### ISSUE TITLE
Load model from resources NOT in asset folder

### ISSUE THREAD

**Issue by Fax3D** [xamarin/urho#153]
Hi,

About Urhosharp and Xamarin.Forms, i think it should be possible to load a 3D model (or any other type of resource) from outside the Asset folder, for example from SD Card or from a file stream taken from internet... 
This could be a very useful features for creating application that dont' rely only on pre-packaged resources, but need to use a more dynamic way to visualize 3D objects.

Thanks.

**Comment by Fax3D** [comment]
I found a solution (for Android), and i want to share with you:

To load a custom .mdl model from SD card, it's simple:

`var javafile = Android.OS.Environment.GetExternalStoragePublicDirectory(Android.OS.Environment.DirectoryDownloads);
            string localPath = Path.Combine(javafile.AbsolutePath, "Models");

            StaticModel _obj = baseNode.CreateComponent<StaticModel>();
            _obj.Model = ResourceCache.GetModel(localPath + "/" + mModelToLoad.name + ".mdl");`

**Comment by deakjahn** [comment]
This shouldn't be closed. There is a need to do this on all platforms.

**Comment by deakjahn** [comment]
Alternative that doesn't work, either:

      var model = modelNode.CreateComponent<StaticModel>();
      model.Model = new Model(Context);
      model.Model.BeginLoad(new Urho.IO.File(Context, "path"));
      model.Model.EndLoad();
