### ISSUE TITLE
Missing MemoryBuffer, cannot load texture from RAM

### ISSUE THREAD

**Issue by xaviergonz** [xamarin/urho#155]
I'd like to load a texture from ram instead of from disk, and while Urho3d supports this (via the Deserializer parameter -> File / MemoryBuffer), UrhoSharp forces me to use File.

Would it be possible to add MemoryBuffer?

**Comment by xaviergonz** [comment]
Now that I think about it, probably it would be even better if there was a managed c++ class that implemented the Urho Deserializer and Serializer classes and wrapped a managed Stream around it.

**Comment by EgorBo** [comment]
Done, 
https://github.com/xamarin/urho/blob/master/Bindings/Portable/MemoryBuffer.cs
ctor accepts byte[] or MemorySteam.

**Comment by xaviergonz** [comment]
This sounds awesome, thank you!!
