### ISSUE TITLE
Bug 44194 - UrhoSharp.Forms render quality is very low

### ISSUE THREAD

**Issue by rmarinho** [xamarin/urho#156]
Porting a issue from [Bugzilla 44194](https://bugzilla.xamarin.com/show_bug.cgi?id=44194) from @praeclarum , will be best followed up here with @EgorBo 

[link to sample project](https://bugzilla.xamarin.com/attachment.cgi?id=17416)

> When I use UrhoSharp.Forms, the UrhoSurface produces very bad renderings.
> 
> The most notable problems are low resolution and color banding.
> 
> The resolution problems seems to come from the UrhoSurface ignoring the UIScreen.Scale. This produces huge pixels on any iOS device.
> 
> The color banding has me confused - almost like 16-bit color is being used. I really don't know what's going on with it.
> 
> Please run the attached project on an iPad and you will see the problems. It will render a pink box with jagged edges and bad colors.
> 
> 
> === Xamarin Studio Enterprise ===
> 
> Version 6.0.2 (build 73)
> Installation UUID: 033a3a98-f63f-44a3-8bd3-bb3b731f3639
> Runtime:
> 	Mono 4.4.2 (mono-4.4.0-branch-c7sr1/f72fe45) (64-bit)
> 	GTK+ 2.24.23 (Raleigh theme)
> 
> 	Package version: 404020011
> 
> === Xamarin.Profiler ===
> 
> Version: 0.32.0
> Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
> 
> === Xamarin.Android ===
> 
> Version: 6.1.2.21 (Xamarin Enterprise)
> Android SDK: /Users/fak/Library/Developer/Xamarin/android-sdk-mac_x86
> 	Supported Android versions:
> 		2.3   (API level 10)
> 		4.0.3 (API level 15)
> 		4.3   (API level 18)
> 		4.4   (API level 19)
> 		5.0   (API level 21)
> 		5.1   (API level 22)
> 		6.0   (API level 23)
> 
> SDK Tools Version: 24.4.1
> SDK Platform Tools Version: 23.1
> SDK Build Tools Version: 19.1
> 
> Java SDK: /usr
> java version "1.8.0_20-ea"
> Java(TM) SE Runtime Environment (build 1.8.0_20-ea-b23)
> Java HotSpot(TM) 64-Bit Server VM (build 25.20-b22, mixed mode)
> 
> Android Designer EPL code available here:
> https://github.com/xamarin/AndroidDesigner.EPL
> 
> === Xamarin Android Player ===
> 
> Version: 0.3.7
> Location: /Applications/Xamarin Android Player.app
> 
> === Apple Developer Tools ===
> 
> Xcode 7.3.1 (10188.1)
> Build 7D1014
> 
> === Xamarin.iOS ===
> 
> Version: 9.8.2.22 (Xamarin Enterprise)
> Hash: f37444a
> Branch: cycle7-sr1
> Build date: 2016-07-28 12:17:02-0400
> 
> === Xamarin.Mac ===
> 
> Version: 2.8.2.22 (Xamarin Enterprise)
> 
> === Xamarin Inspector ===
> 
> Version: 0.8.0.0
> Hash: dc081aa
> Branch: master
> Build date: Tue Apr 26 23:07:44 UTC 2016
> 
> === Build Information ===
> 
> Release ID: 600020073
> Git revision: a6f7a24a9723a2d4f5d33c176615b0d44703ab5b
> Build date: 2016-07-26 13:36:15-04
> Xamarin addins: f5acb37866a0141bc5ddbe95118f18dae4014568
> Build lane: monodevelop-lion-cycle7-sr1
> 
> === Operating System ===
> 
> Mac OS X 10.12.0
> Darwin muon.local 16.0.0 Darwin Kernel Version 16.0.0
>     Mon Aug 29 17:56:20 PDT 2016
>     root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64
> 
> === Enabled user installed addins ===
> 
> Xamarin Inspector 0.8.0.0

**Comment by AndreJFBico** [comment]
+1 also suffering from a similar issue in IOS.

**Comment by rmarinho** [comment]
Funny @AndreJFBico just found your profile a few days ago looking at people from Storyo on git :)

**Comment by AndreJFBico** [comment]
Oh @rmarinho , good to know ;)

**Comment by EgorBo** [comment]
I am investigating this.

**Comment by EgorBo** [comment]
1) Urho3D has "HighDPI" flag disabled by default for some reason, I enabled it in the master (will be available within next nuget update). But as a workaround you can test it now via ApplicationOptions: `options.AdditionalFlags = " -hd"`
2) If you use png textures - make sure "Optimize PNG images" is disabled in the project settings
3) To fix "jagged edges" you can apply built-in FXAA2 post-process effect:
`Renderer.GetViewport(0).RenderPath.Append(CoreAssets.PostProcess.FXAA2);`
4) Render quality (those bad colors) can be different on a simulator and on a device. iOS simulator doesn't really provide the same graphics system to debug opengles applications so those bad colors will disappear on a real device.

**Comment by Abhijeet-Xamarin** [comment]
@EgorBo 

on iOS specifically rendering is very slow & texture color rendering different (blue insted of orange), what could be the reasons ?

**Comment by EgorBo** [comment]
@Abhijeet-Xamarin 
Make sure "PNG Optimization" is disabled in your iOS project's properties.
What you mean by "slow", what device do you use?

**Comment by Abhijeet-Xamarin** [comment]
@EgorBo, Thanks for responding. 

Slow: Animation (roatation of model), but the issue was only in the simulator - On Actual device it is working as expected. 

> Make sure "PNG Optimization" is disabled in your iOS project's properties. 

- This has resolved the color issue, but only on actual device.

**Comment by deakjahn** [comment]
_To fix "jagged edges" you can apply built-in FXAA2 post-process effect:
Renderer.GetViewport(0).RenderPath.Append(CoreAssets.PostProcess.FXAA2);_

Is there a way to check if this is actually supported? Might not be a problem on mobile but older video cards on UWP could give problems.
