### ISSUE TITLE
Class library to target both hololens and desktop/uwp etc

### ISSUE THREAD

**Issue by CZEMacLeod** [xamarin/urho#158]
I have a class library, which in and of itself, uses the Urho namespaces and objects to build various geometries and other functions. It seems to compile with either `"UrhoSharp.HoloLens": "1.1.14.2"` or `"UrhoSharp": "1.1.125"` but if I use the latter then try to add it to a HoloLens application it doesn't work (transitive restore and duplicate file/dll names).

I don't know how much overlap and difference there is with the HoloLens UrhoSharp compile compared to the standard lib, but would it be possible to make the HL package depend on the main package and have a different assembly name containing only the additional stuff? Otherwise is there any way of making my project(s) target both without major editing and re-compiling?

**Comment by EgorBo** [comment]
@CZEMacLeod within next UrhoSharp nuget update you will be able to do use both packages. I mean, for example:
PCL - UrhoSharp
Desktop - PCL, UrhoSharp
HoloLens - PCL, UrhoSharp.HoloLens.

**Comment by EgorBo** [comment]
Can be done now with 1.1.214 pacakge
HoloApplicaton is inside the PCL and can used on other platforms as well
