### ISSUE TITLE
iOS - Improve error checking for texture sizes.

### ISSUE THREAD

**Issue by matachi** [xamarin/urho#163]
I'm trying to display a .bmp image, but it doesn't appear on iOS. It works fine on Android though. Here are a couple of screenshots, where I have added a .dds image from the FeatureSamples project as a reference (which works on both platforms):

![10](https://cloud.githubusercontent.com/assets/980838/19558975/8fd68b44-96cd-11e6-9106-c94b24975042.JPG)

![11](https://cloud.githubusercontent.com/assets/980838/19558978/92c8c240-96cd-11e6-93f8-e94afcb95096.JPG)

The code for displaying the images is available at https://github.com/matachi/urhosharp-load-resources/blob/master/TestApp/TestApp/MainPage.xaml.cs#L51-L65.

**Comment by EgorBo** [comment]
@matachi your texture should be power-of-two for iOS.

**Comment by EgorBo** [comment]
resize it to something like 512*256 and it'll show up.

**Comment by matachi** [comment]
Thanks, that did the trick!

Just wondering though, would it be possible to make it so it doesn't fail silently?

**Comment by EgorBo** [comment]
Fixed by https://github.com/xamarin/Urho3D/compare/90f398d80c90806a6398d5f50d284d7261c8df3b...95151b5d59aeba4f419e0ea2e9e60170d7002bf6#diff-0a849acc7a05fff203eb72ec5c91a46bR86 (it eventually will trigger an unhandled exception with that text in C#).

**Comment by Abhijeet-Xamarin** [comment]
@EgorBo, I am facing same issue & it did got resolved when I change the image size to power of 2. But texture is rendering different color than Android & UWP. 

Can you please guide me for same? 

Urho.Forms version 1.5.22
