### ISSUE TITLE
templates broken?

### ISSUE THREAD

**Issue by nictaylr** [xamarin/urho#169]
I tried the official template link: <https://marketplace.visualstudio.com/items?itemName=EgorBogatov.UrhoSharpTemplates> and installed it. According to the README, a project should be created for each platform. However, I only got a universal desktop project:

![image](https://cloud.githubusercontent.com/assets/22607541/20508304/8201d792-b015-11e6-959a-c2c746b3e77c.png)

Perhaps the templates are broken?

**Comment by EgorBo** [comment]
@nictaylr there are two kind of templates:
1) UrhoSharp 
2) UrhoSharp for HoloLens
the second one creates only UWP for HoloLens project. And it looks like this is your case.

**Comment by nictaylr** [comment]
thanks, you solved my problem. i had accidentally used the HoloLens template.
