### ISSUE TITLE
how to set window size on desktop platform?

### ISSUE THREAD

**Issue by nictaylr** [xamarin/urho#170]
i would like to set a fixed size for my game on desktop plaforms: for example, like `800x600`. on mobile, i want the game to be fullscreen.

how can i set the window size on desktop platform?

thanks!

**Comment by EgorBo** [comment]
@nictaylr 
`ApplicationOptons { Width = 800, Height = 600 }`
it will affect only Windows (also, you can play with Resize parameter)
