### ISSUE TITLE
Color and Material Anomalies

### ISSUE THREAD

**Issue by charlespetzold** [xamarin/urho#172]
The `Color` property of `Shape` and the `SetMaterial` method with a `Material.FromColor` object work inconsistently, and neither is adequate for cloning assemblies of multiple `Shape` objects, which is often desirable in workbooks.

The problems are demonstrated in the following workbook:

https://github.com/xamarin/private-samples/tree/master/workbooks/urho/ColorIssue.workbook

which is also in the attached file:

[ColorIssue.workbook.zip](https://github.com/xamarin/urho/files/637529/ColorIssue.workbook.zip)

**Comment by EgorBo** [comment]
Hello Charles, I am sorry I didn't notice this issue.
I think I fixed issues you mentioned in the workbook (the greatest bug report ever 😄)
Clone issues - fixed few month ago.
Color issues - as you suggested I now set NoTexture if Color doesn't have a custom alpha (basically Color now uses Material.FromColor).
