### ISSUE TITLE
User control scene rendering update

### ISSUE THREAD

**Issue by vutle** [xamarin/urho#174]
Hi I'm beginning to make a winform application and wonder how would I use UrhoSharp as a rendering engine.
E.g. The user will tell the engine to perform a rendering update. This allows us to update nodes transformation without rendering.

Thanks

**Comment by migueldeicaza** [comment]
I think it might be best to take this issue to the Forums where other folks are discussing these things.   I am afraid that this is not the right venue for this, as there is no off-the-shelf answer right now, some research and discussion is needed.

**Comment by EgorBo** [comment]
@vutle 
1) in Feature-Samples you can find a winforms integration sample
2) you can control the game loop yourself:
- set applicationOptions.DelayedStart = true
- call myGame.Engine.RunFrame() whenever you want, just make sure you are on the UI thread.
