### ISSUE TITLE
UrhoSharp doesn't have methods from GPUObject

### ISSUE THREAD

**Issue by gleblebedev** [xamarin/urho#176]
The code of SharpieBinder has the following comment:
```
// 
// Only a (File, MemoryBuffer, VectorBuffer)
// implement that, and the Serializer class is never
// surfaced as an API entry point, so we should just inline the methods
// from those classes into the generated class
//
if (baseName == "GPUObject" || baseName == "Thread" || baseName == "Octant" ||
	baseName == "b2Draw" || baseName == "b2ContactListener" || baseName == "btIDebugDraw" || baseName == "btMotionState")
	continue;
```

But even then there is no GPUObject methods in Texture class. The one I'm missing the most is GetGPUObjectName.

Could you please fix that and add GPUObject method bindings to it's child classes?

**Comment by EgorBo** [comment]
Fixed.
All GPUObject subclasses now have "AsGPUObject()" method.
for example,
var n = texture.AsGPUObject().GPUObjectName;
