### ISSUE TITLE
The "Localization" is not ported ?

### ISSUE THREAD

**Issue by hedgehed** [xamarin/urho#177]
Hi
I want to use localization engine, but it not implemented yet.
In UrhoSharp i cannot use 
`LoadJSONFile("Strings/StringsEnRu.json");` 
Also not present mechanism for linking AppResources.resx to urho.

But when i load xml with UI interface - i see in debug log:
`
Searching for 'UIElement_GetName'.
Probing 'UIElement_GetName'.
Found as 'UIElement_GetName'.
Localization::Get(id): no loaded languages
Localization::Get(id): no loaded languages
`

Help me please, how to quick (and dirty) make the localization of text elements in UrhoSharp ?
Maybe something like 
`
		[DllImport("mono-urho", CallingConvention = CallingConvention.Cdecl)]
		internal static extern void LoadJSONFile(string name);
`
(good idea but not works)

**Comment by EgorBo** [comment]
Added in c2f96506fdaf104ce48546aec7e6672d7b2e2398 and 0faa67846ffc1c4dc5e5906ddc7dd308f78d8208

**Comment by RayKoopa** [comment]
Dumb question, how do I access the `Localization` subsystem? There doesn't seem to be a handy property on `Context`, and `var localization = (Localization)Context.GetSubsystem(Localization.TypeStatic);` can't be casted.
