### ISSUE TITLE
Application with urhosurface randomly crash when navigating back on Android

### ISSUE THREAD

**Issue by MichalPetryk** [xamarin/urho#178]
My application randomly crash when navigating back to previous page from page which contains UrhoSurface. Before navigating back i always call awaitable Exit() method, but sometimes i got an error (1 out of 10):

<pre>
01-24 00:55:01.995 W/URHOSHARP(16394): App exited: 0
01-24 00:55:01.995 W/dalvikvm(16394): Invalid indirect reference 0x69bc0368 in decodeIndirectRef
01-24 00:55:01.995 I/dalvikvm(16394): "SDLThread" prio=5 tid=21 RUNNABLE
01-24 00:55:01.995 I/dalvikvm(16394):   | group="main" sCount=0 dsCount=0 obj=0x42a60dc0 self=0x69b99490
01-24 00:55:01.995 I/dalvikvm(16394):   | sysTid=16452 nice=0 sched=0/0 cgrp=apps handle=1552927992
01-24 00:55:01.995 I/dalvikvm(16394):   | state=R schedstat=( 33222679859 10885659701 134970 ) utm=2408 stm=914 core=0
01-24 00:55:01.995 I/dalvikvm(16394):   at java.lang.System.identityHashCode(Native Method)
01-24 00:55:01.995 I/dalvikvm(16394):   at org.libsdl.app.SDLActivity.nativeInit(Native Method)
01-24 00:55:01.995 I/dalvikvm(16394):   at org.libsdl.app.SDLMain.run(SDLActivity.java:876)
01-24 00:55:01.995 I/dalvikvm(16394):   at java.lang.Thread.run(Thread.java:841)
01-24 00:55:01.995 I/dalvikvm(16394): 
01-24 00:55:01.995 E/dalvikvm(16394): VM aborting
01-24 00:55:01.995 E/mono-rt (16394): Stacktrace:
01-24 00:55:01.995 E/mono-rt (16394): 
01-24 00:55:01.995 E/mono-rt (16394):   at <unknown> <0xffffffff>
01-24 00:55:01.995 E/mono-rt (16394):   at (wrapper managed-to-native) Android.Runtime.JNIEnv._monodroid_get_identity_hash_code (intptr,intptr) <IL 0x0002a, 0xffffffff>
01-24 00:55:01.995 E/mono-rt (16394):   at Android.Runtime.JNIEnv.<Initialize>m__0 (intptr) [0x00000] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.cs:203
01-24 00:55:01.995 E/mono-rt (16394):   at Java.Lang.Object.GetObject (intptr,Android.Runtime.JniHandleOwnership,System.Type) [0x00022] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/src/Java.Lang/Object.cs:352
01-24 00:55:01.995 E/mono-rt (16394):   at Java.Lang.Object._GetObject<T_REF> (intptr,Android.Runtime.JniHandleOwnership) [0x0001a] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/src/Java.Lang/Object.cs:342
01-24 00:55:01.995 E/mono-rt (16394):   at Java.Lang.Object.GetObject<T_REF> (intptr,Android.Runtime.JniHandleOwnership) [0x00000] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/src/Java.Lang/Object.cs:334
01-24 00:55:01.995 E/mono-rt (16394):   at Android.Views.GestureDetector/IOnGestureListenerInvoker.n_OnDown_Landroid_view_MotionEvent_ (intptr,intptr,intptr) [0x00009] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Views.GestureDetector.cs:503
01-24 00:55:01.995 E/mono-rt (16394):   at (wrapper dynamic-method) object.300697e6-fbb8-4c8d-b42b-4259fc1b754d (intptr,intptr,intptr) <IL 0x00017, 0x0004b>
01-24 00:55:01.995 E/mono-rt (16394): 
01-24 00:55:01.995 E/mono-rt (16394): Attempting native Android stacktrace:
01-24 00:55:01.995 E/mono-rt (16394): 
01-24 00:55:02.010 E/mono-rt (16394):   at dvmAbort+67 [0x40b3c2f4]
01-24 00:55:02.010 E/mono-rt (16394):   at dvmDecodeIndirectRef(Thread*, _jobject*)+146 [0x40b40d47]
01-24 00:55:02.010 E/mono-rt (16394):   at dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+154 [0x40b569ff]
01-24 00:55:02.010 E/mono-rt (16394):   at ???+305065 [0x40b407a9]
01-24 00:55:02.010 E/mono-rt (16394):   at _monodroid_get_identity_hash_code+68 [0x590dcd00]
01-24 00:55:02.010 E/mono-rt (16394): 
01-24 00:55:02.010 E/mono-rt (16394): =================================================================
01-24 00:55:02.010 E/mono-rt (16394): Got a SIGSEGV while executing native code. This usually indicates
01-24 00:55:02.010 E/mono-rt (16394): a fatal error in the mono runtime or one of the native libraries 
01-24 00:55:02.010 E/mono-rt (16394): used by your application.
01-24 00:55:02.010 E/mono-rt (16394): =================================================================
01-24 00:55:02.010 E/mono-rt (16394): 
01-24 00:55:02.010 F/libc    (16394): Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1), thread 16452 (SDLThread)
01-24 00:55:11.540 D/Mono    (16394): [0x5c52abb0] worker finishing
</pre>

Installed version of UrhoSharp.Forms is 1.2.21

**Comment by MichalPetryk** [comment]
Hi,

I found temporary solution. I just added:

<pre>
GC.Collect();
GC.WaitForPendingFinalizers();
</pre>

after calling awaitable Exit() method and before navigating back.

It seems to work properly.

**Comment by MichalPetryk** [comment]
Unfortunately above solution doesn't resolve my problem... Still the same error.

**Comment by CJACQUEL** [comment]
Hello, 
Same problem while navigate with Carouselpage, After a a certain number of times, at the end the Urho App page randomly crash.
Could you help ? 
Thank you ,

**Comment by MichalPetryk** [comment]
Hi,
@CJACQUEL please try to put this 2 lines of code:
<pre>YourUrhoSurface.Destroy();
 await Task.Delay(250);</pre>

inside method: <pre>protected override void OnDisappearing()</pre>

**Comment by CJACQUEL** [comment]
There is always the same problem. The Urho application carshe when navigating. Could we expect for a stable version of urho ? 
Thank you,

**Comment by MichalPetryk** [comment]
@CJACQUEL did you check last update of Urho.Forms (1.3.0) and Xamarin.Forms (2.3.4.224)?
It seems to be fixed in last release.

**Comment by MichalPetryk** [comment]
After update Urho.Forms (1.3.0) and Xamarin.Forms (2.3.4.224) a got an error when navigating back:
<pre>
App exited: 0
04-14 13:54:37.931 E/mono    (11615): 
04-14 13:54:37.931 E/mono    (11615): Unhandled Exception:
04-14 13:54:37.931 E/mono    (11615): System.NullReferenceException: Object reference not set to an instance of an object.
04-14 13:54:37.931 E/mono    (11615):   at (wrapper dynamic-method) System.Object:fae6a69d-9caf-4d1b-84a9-2947bd4717a5 (intptr,object[])
In mgmain JNI_OnLoad
04-14 13:54:37.936 E/mono-rt (11615): [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
04-14 13:54:37.936 E/mono-rt (11615):   at <0x00000 + 0x00000> <unknown method>
</pre>

**Comment by MichalPetryk** [comment]
I found another problem... Here is scenario:

- i have page with urho surface and navigate to another page containing ScrollView (Xamarin.Forms Control)
- i pop the page with ScrollView and back to page with urho
- when i want to leave the page with urho i call UrhoSurface.Destroy() method and get error:

<pre>
 App exited: 0
05-18 14:18:42.621 E/mono-rt (22203): Stacktrace:
05-18 14:18:42.621 E/mono-rt (22203): 
05-18 14:18:42.621 E/mono-rt (22203):   at <unknown> <0xffffffff>
05-18 14:18:42.621 E/mono-rt (22203):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_get_java_vm (intptr,intptr&) <0x0003f>
05-18 14:18:42.621 E/mono-rt (22203):   at Java.Interop.JniEnvironment/References.GetJavaVM (intptr,intptr&) [0x00003] in /Users/builder/data/lanes/4468/b16fb820/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.cs:168
05-18 14:18:42.621 E/mono-rt (22203):   at Java.Interop.JniEnvironmentInfo.set_EnvironmentPointer (intptr) [0x00044] in /Users/builder/data/lanes/4468/b16fb820/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.cs:198
05-18 14:18:42.621 E/mono-rt (22203):   at Java.Interop.JniEnvironment.SetEnvironmentPointer (intptr) [0x00007] in /Users/builder/data/lanes/4468/b16fb820/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.cs:46
05-18 14:18:42.621 E/mono-rt (22203):   at Java.Interop.JniTransition..ctor (intptr) [0x00010] in /Users/builder/data/lanes/4468/b16fb820/source/Java.Interop/src/Java.Interop/Java.Interop/JniTransition.cs:15
05-18 14:18:42.621 E/mono-rt (22203):   at Android.Runtime.JNIEnv.CheckHandle (intptr) [0x00000] in /Users/builder/data/lanes/4468/b16fb820/source/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:109
05-18 14:18:42.621 E/mono-rt (22203):   at Java.Lang.Object.GetObject<T_REF> (intptr,intptr,Android.Runtime.JniHandleOwnership) [0x00000] in /Users/builder/data/lanes/4468/b16fb820/source/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:415
05-18 14:18:42.621 E/mono-rt (22203):   at Android.Views.View.n_OnScrollChanged_IIII (intptr,intptr,int,int,int,int) [0x00000] in /Users/builder/data/lanes/4468/b16fb820/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.Views.View.cs:15340
05-18 14:18:42.621 E/mono-rt (22203):   at (wrapper dynamic-method) object.ebf98a5d-bdbe-4ca4-b0ef-a8b23c7a575d (intptr,intptr,int,int,int,int) [0x00029] in <8c304e4006094a46a7950338a3b3cb5d>:0
....
No native Android stacktrace (see debuggerd output).
05-18 14:18:42.651 E/mono-rt (22203): 
05-18 14:18:42.651 E/mono-rt (22203): 
05-18 14:18:42.651 E/mono-rt (22203): =================================================================
05-18 14:18:42.651 E/mono-rt (22203): Got a SIGSEGV while executing native code. This usually indicates
05-18 14:18:42.651 E/mono-rt (22203): a fatal error in the mono runtime or one of the native libraries 
05-18 14:18:42.651 E/mono-rt (22203): used by your application.
05-18 14:18:42.651 E/mono-rt (22203): =================================================================
05-18 14:18:42.651 E/mono-rt (22203): 
05-18 14:18:42.651 F/libc    (22203): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 22258 (SDLThread)
</pre>

If i leave urho page without calling UrhoSurface.Destroy() no errors occur.

**Comment by sabvente** [comment]
We also had an issue with back navigation. Our application crashed right after the `AppCompatActivity.OnPause` call. The `AppCompatActivityDestory` hasn't been called.

Trace:
```A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x100000001 in tid 26464 (SDLThread)```

Our temporary solution was to call `Urho.Application.Current.Exit();` in `DispatchKeyEvent` (where we handled back key press).

Ver: UrhoSharp 1.4.47

**Comment by EgorBo** [comment]
@sabvente сould you share some repro project I can test?

**Comment by sabvente** [comment]
@EgorBo I created a stripped-down version of out project.

How can you repro:
1. Start app
2. Click button to open urho (this is an empty application)
3 Press soft back button (not the actionbar back)
4. Repeat steps 2-3 for 15 times
5. After the 15th back press, the app crashes

Tested on Nexus 5X 7.1.2

https://github.com/sabvente/urho-test

Thank you

**Comment by EgorBo** [comment]
@sabvente thanks!!

**Comment by EgorBo** [comment]
Should be fixed in the recent releases.  Android support was significantly improved.

**Comment by prasanth1216** [comment]
> Hi,
> @CJACQUEL please try to put this 2 lines of code:
> 
> YourUrhoSurface.Destroy();
>  await Task.Delay(250);
> inside method:
> 
> protected override void OnDisappearing()

I face the similar issue in UrhoSharp.Forms (1.9.67), but with this solution, the issue got resolved.
