### ISSUE TITLE
return value will be uncorrect

### ISSUE THREAD

**Issue by xiliu98** [xamarin/urho#181]
DllExport const class Urho3D::IntRect &
Sprite2D_GetRectangle (Urho3D::Sprite2D *_target)
DllExport const class Urho3D::IntRect &
Graphics_GetScissorRect (Urho3D::Graphics *_target)

when I invoke GetRectangle , it will return uncorrect value, mostly is 0.
I removed the '&' symbol,  and test,  the value is correct.
sorry for my bad english.

**Comment by EgorBo** [comment]
Confirmed & fixed in master.
