### ISSUE TITLE
UwpSurfaceRenderer -- an exception being thrown (but hidden)

### ISSUE THREAD

**Issue by daniel-packard** [xamarin/urho#183]
Hi -- I'm opening an issue here related to a xamarin forum post: 
* https://forums.xamarin.com/discussion/comment/239946#Comment_239946

> In the UwpSurfaceRenderer a exception was being thrown and hidden (when back button was pressed) and propagated in other cases (when the main navigation page is replaced).

@kylecolden has recommended a solution to update this piece of code:  
* https://github.com/xamarin/urho/blob/72bf3bd18aa29c2b2bf1d08ef0eda063711a7c7e/Bindings/Forms/UwpSurfaceRenderer.cs#L14-L20

To the following:
```
protected override void OnElementChanged(ElementChangedEventArgs<UrhoSurface> e)
{
    if (e.NewElement != null)
    {
        urhoSurface = new Urho.UWP.UrhoSurface();
        e.NewElement.UrhoApplicationLauncher = UrhoLauncher;
        SetNativeControl(urhoSurface);
    }
    base.OnElementChanged(e);
}
```

We  haven't opened a PR yet since we're on a constrained timeline

**Comment by daniel-packard** [comment]
Note - we've been running this change in a custom local build for some time now, it seems stable.

**Comment by kylecolden** [comment]
I'll also point out that the various base classes for ViewRenderers in Xamarin.Forms.Platform.UWP/Android/iOS dlls all expect conditions where the NewElement is null in their OnElementChanged.

Example: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.WinRT/ViewRenderer.cs#L24

And none of the corresponding Urho Surface Renderers handle that condition.

So, this may be an issue beyond just UWP.

**Comment by EgorBo** [comment]
Thanks for noticing that!

**Comment by daniel-packard** [comment]
And thanks for fixing it! 😁
