### ISSUE TITLE
Extract Graphic Engine

### ISSUE THREAD

**Issue by AymericLambolez** [xamarin/urho#188]
Hi everyone,

We're currently developping an app in C#, using WPF on Windows, and MonoMac for OSX. We now need to add a 3D view for our project, and were looking out to use Urho, as it seems really interesting.
The thing is, we don't need to integrate every part of the Engine, only the Graphic engine would be enough.
Does anyone knows a way to extract the Graphic Engine, or just have another way around to use Urho Graphic Engine inside our app ?
The way it seems to work is that we have to integrate our app into Urho, not Urho into our app.

Thanks

**Comment by EgorBo** [comment]
@AymericLambolez 
UrhoSharp can be integrated into any existing .net app as a widget. Just take a look at the feature-samples, Urho is integrated there in WPF and CocoaApp as a Panel and an NSView.

Also you can control the game loop yourself if you need it (and call 'await Task.Delay()' between frames for example).

**Comment by migueldeicaza** [comment]
Egor is exactly right, you can achieve what you want with Urhosharp.

In my opinion, extracting the Graphics Engine is just not worth it.  It is something that you can try if you insist, and you would do that by forking the Urho code and the bindings bindings to remove anything that you do not need.

**Comment by AymericLambolez** [comment]
Ok thank you, I will dig into that and see if spliting the engine is really needed.

I've been able to integrate Urho into my app as needed, thanks to both of you for your answers
