### ISSUE TITLE
Package Manifest Generated by Visual Studio HoloLens Template Won't Open

### ISSUE THREAD

**Issue by sschaub** [xamarin/urho#189]
With Visual Studio 2015 Update 3:

Repro steps:

1. Create new application using UrhoSharp for HoloLens template.
2. After new project is created, attempt to open Package.appxmanifest in Visual Studio Solution Explorer.

Expected: Package Manifest designer opens and displays attributes of manifest
Actual: Message "Unable to Load Manifest Designer - The Manifest Designer cannot load because one or more files has errors." appears.

**Comment by EgorBo** [comment]
AFAIK, that was because of added 'spatial mapping' capability. Not sure I can fix that.

**Comment by migueldeicaza** [comment]
Can you explain what the above message means Egor?

**Comment by EgorBo** [comment]
The VS Appxmanifest viewer used to crash while opening our Package.appxmanifest file but it was 100% valid for compile+deploy+run on a device. But I've found out I forgot to add uap2 namespace to IgnorableNamespaces attribute. See https://github.com/xamarin/urho/commit/515f3f57b06a839bae1d767beba12d5509f62210 - it has fixed the issue.
