### ISSUE TITLE
Trouble creating runtime Model

### ISSUE THREAD

**Issue by AymericLambolez** [xamarin/urho#190]
Hi everyone,

For my app, I need to open custom 3D files.
I am then trying to create a new geometry based on the file data, but I happen to have some trouble with that...

For now, I have my Static Mesh, with the right Model inside and the correct Geometry in this Model.
This Geometry contains my VertexBuffers and IndexBuffer correctly, so everything seems fine.

However, nothing shows up on my screen... I guess there is some function I forgot to call, but I can't find wich one.

Here's my code, and yes, I apologize for the density of this one, it will get a nice refactoring once I will get everything working.

        private static void ParseGeometry(object context, UrhoObject node)
        {
            //Context should be a Dictionnary containing:
            // "vertexFormat" : int 
            // "vertexStream" : byte[]
            // "indexStream"  : byte[]
            Dictionary<string, object> dico = context as Dictionary<string, object>;
            if (dico == null ||
                !dico.ContainsKey("vertexFormat") || !dico.ContainsKey("vertexStream") || !dico.ContainsKey("indexStream"))
            {
                SphereException exception = new SphereException((int)Error.GlobalError.InternalError, "Error while parsing the TWD file");
                Logs.WriteLog(null, exception);
                throw exception;
            }

            // A Dictionnary representing VertexBuffer for each mask. The int of the Tuple indicates the number of float needed for each element of this array
            Dictionary<ElementMask, Tuple<int, VertexBuffer>> vertexBuffers = new Dictionary<ElementMask, Tuple<int, VertexBuffer>>();

            // A Dictionnary representing the arrays for each mask
            Dictionary<ElementMask, float[]> vBuffers = new Dictionary<ElementMask, float[]>();
            IndexBuffer indexBuffer = new IndexBuffer(Application.CurrentContext, false);

            byte[] formerIndexBuffer = (byte[])dico["indexStream"];
            short[] iBuff = new short[formerIndexBuffer.Length / 4];
            uint indexNum = (uint)formerIndexBuffer.Length / 4;
            for (int i = 0; i < indexNum; ++i)
                iBuff[i] = BitConverter.ToInt16(formerIndexBuffer, i * 4);
            indexBuffer.SetSize(indexNum, false, false);
            indexBuffer.SetData(iBuff);

            // This byte array represents the complete data of the mesh, concataining Position, Normal, Color and more
            // We can know what's inside by checking the vertexFormat
            byte[] formerVertexBuffer = (byte[])dico["vertexStream"];
            int vertexFormat = (int)dico["vertexFormat"];
            int vertexSize = 0;
            if ((vertexFormat & (int)TWDVertexFormat.XYZ) == (int)TWDVertexFormat.XYZ)
            {
                vertexSize += 3;
                vertexBuffers[ElementMask.Position] = new Tuple<int, VertexBuffer>(3, new VertexBuffer(Application.CurrentContext, false));
            }
            if ((vertexFormat & (int)TWDVertexFormat.RGB) == (int)TWDVertexFormat.RGB)
            {
                vertexSize += 3;
                vertexBuffers[ElementMask.Color] = new Tuple<int, VertexBuffer>(3, new VertexBuffer(Application.CurrentContext, false));
            }
            else if ((vertexFormat & (int)TWDVertexFormat.RGBA) == (int)TWDVertexFormat.RGBA)
            {
                vertexSize += 4;
                vertexBuffers[ElementMask.Color] = new Tuple<int, VertexBuffer>(4, new VertexBuffer(Application.CurrentContext, false));
            }
            if ((vertexFormat & (int)TWDVertexFormat.Normal) == (int)TWDVertexFormat.Normal)
            {
                vertexSize += 3;
                vertexBuffers[ElementMask.Normal] = new Tuple<int, VertexBuffer>(3, new VertexBuffer(Application.CurrentContext, false));
            }
            if ((vertexFormat & (int)TWDVertexFormat.Tangent) == (int)TWDVertexFormat.Tangent)
            {
                vertexSize += 4;
                vertexBuffers[ElementMask.Tangent] = new Tuple<int, VertexBuffer>(4, new VertexBuffer(Application.CurrentContext, false));
            }
            if ((vertexFormat & (int)TWDVertexFormat.UV) == (int)TWDVertexFormat.UV)
            {
                vertexSize += 2;
                vertexBuffers[ElementMask.TexCoord1] = new Tuple<int, VertexBuffer>(2, new VertexBuffer(Application.CurrentContext, false));
            }
            uint vertexNum = (uint)formerVertexBuffer.Length / (uint)vertexSize / 4;

            // The dictionnary contains only the masks corresponding to the vertexFormat of this file
            foreach (ElementMask mask in vertexBuffers.Keys)
            {
                // We set the size of the vertex buffer and creates the appropriate float array
                vertexBuffers[mask].Item2.SetSize(vertexNum, mask, false);
                vBuffers[mask] = new float[vertexNum * vertexBuffers[mask].Item1];
            }
            for (int i = 0; i < vertexNum; i++)
            {
                int index = i * 4 * vertexSize;
                foreach (ElementMask key in vBuffers.Keys)
                {
                    //The Item1 of the Tuple represents the number of float needed for this vertex Buffer
                    // (3 for Position, 2 for UV, 4 for Tangent, etc...)
                    int floatNum = vertexBuffers[key].Item1;
                    for (int val = 0; val < floatNum; ++val)
                    {
                        vBuffers[key][i * floatNum + val] = BitConverter.ToSingle(formerVertexBuffer, index);
                        index += 4;
                    }
                }
            }

            Geometry geometry = new Geometry();
            geometry.SetNumVertexBuffers((uint)vertexBuffers.Count);
            uint ind = 0;
            foreach (ElementMask key in vBuffers.Keys)
            {
                vertexBuffers[key].Item2.SetData(vBuffers[key]);
                geometry.SetVertexBuffer(ind, vertexBuffers[key].Item2);
                ind++;
            }
            geometry.IndexBuffer = indexBuffer;
            geometry.SetDrawRange(PrimitiveType.TriangleList, 0, indexNum, false);
            Model model = new Model();
            model.NumGeometries = 1;
            model.SetGeometry(0, 0, geometry);
            model.SetNumGeometryLodLevels(0, 1);
            ((Node)node).GetOrCreateComponent<StaticModel>().Model = model;
        }

After that I attach my Node to an empty one, and attach the empty to the scene.

It may be some stupid mistake that I don't spot, but right now I'm completely blind on it.

If anyone has an idea about what is missing or wrong, please let me know !

Thank you !

**Comment by AymericLambolez** [comment]
I solved my issue, I rewrote everything so not sure where was exactly the problem, but I'm pretty sure it's because I didn't have set a bounding box to my object, so it was not in the scope of the camera.

Also, I concatenated all my vertex buffers into one.

**Comment by JimSEOW** [comment]
@AymericLambolez can you share the working code?
