### ISSUE TITLE
Frustum struct is empty

### ISSUE THREAD

**Issue by iainmerrick** [xamarin/urho#191]
The Camera class has some methods that return a Frustum, but Frustum in the C# bindings is just an empty struct.

**Comment by iainmerrick** [comment]
I can take a crack at this if somebody can give me a few pointers to get started! I'm not sure whether we need to re-implement Frustum, or wrap the C++ class. The existing structs don't seem consistent so it's not clear what the best practice is; the Quaternion class especially seems to be in flux.

**Comment by iainmerrick** [comment]
Matrix3x4 (returned by Camera.EffectiveWorldTransform, and used to initialize the Frustum) is also mostly unimplemented in the C# bindings.

**Comment by EgorBo** [comment]
Added Frustum with all members (vertices_ and planes_ were surfaced as properties).
