### ISSUE TITLE
Logging on OSX

### ISSUE THREAD

**Issue by wvdvegt** [xamarin/urho#198]
I created a simple project (Desktop/Android/iOS)

In the shared code I added 

`LogSharp.Log.Debug("Start");
`
And that works on Windows, but fails to show anything on OSX (not in the console window used to start, not the Urho3D.log file that's generated.

`Log.Write(LogLevel.Warning,` "Could not find bone for creating ragdoll physics components");

Just fails to output on windows as well.

Documentation is not very clear on what to use, Log/LogSharp and what methods.

**Comment by EgorBo** [comment]
@wvdvegt which version of urho do you use? LogSharp is internal. Unlike the `Log`, LogSharp doesn't use pinvokes (needed to log some stuff before mono-urho is loaded)

**Comment by wvdvegt** [comment]
@EgorBo  
Using: 
UrhoSharp v1.2.21
LogSharp v1.0.7

I needed to add LogSharp as a separate package in order to use it, so I do not get what you mean by 'internal'. I noticed it seems to ends up in a logfile urho3d.log. 

What i was looking for is to output to the console window (the one where i start the exe on osx using mono) attached the game (for debugging purposes).

**Comment by migueldeicaza** [comment]
This does not seem to be an Urho related issue, but a problem with LogSharp when running on Mono/Mac.
