### ISSUE TITLE
Enable multisampling

### ISSUE THREAD

**Issue by Jaroost** [xamarin/urho#200]
Hello,

I have trouble enabling the multisampling in the application.

I use the SetMode method: 
`var ret=Graphics.SetMode(1920, 1080, false, true, false, false, false, false, 8);`

ret indicate that the change is OK (true)

I use the `SetMode` in the `Start` method of an `Urho.Application`

But the multisampling doesn't seem to be activated please see the 3 join images:

- without_set_mode.png --> no call to `SetMode` , graphical card not modified
![with_set_mode](https://cloud.githubusercontent.com/assets/12050463/24601711/48ace52e-185a-11e7-991c-00b70077f4f9.png)

- with_set_mode.png      --> call to `SetMode` return true, graphical card not modified
![without_set_mode](https://cloud.githubusercontent.com/assets/12050463/24601710/48abcba8-185a-11e7-8f2d-354475edbc69.png)

- graphical_card_8x.png  --> no call to 'SetMode', grahical card modified to 8x multisampling
![graphical_card_8x](https://cloud.githubusercontent.com/assets/12050463/24601709/48ab56dc-185a-11e7-891c-1872dba0bb03.png)

I use UrhoSharp in a WPF application.

Bye.

**Comment by EgorBo** [comment]
@Jaroost can you please try setting it via ApplicationOptions and check if it works? (it does for me):
new ApplicationOptions("Data") { AdditionalFlags = "-m 8" }

**Comment by Jaroost** [comment]
Hello,

I see the problem:

When I use the parameter `ExternalWindow`, `SetMode` or `AdditionalFlags = "-m 8"` it doesn't work : 
```
var urhoSurface = new Panel { Dock = DockStyle.Fill };
WindowsFormsHost.Child = urhoSurface;
WindowsFormsHost.Focus();
urhoSurface.Focus();
await Task.Yield();
var appOptions = new Urho.ApplicationOptions("Data")
            {
                ExternalWindow = urhoSurface.Handle,
                AdditionalFlags = "-m 8"                
            };
```

But when I remove `ExternalWindow` it works (for both `SetMode` and `AdditionalFlags`).

Is it a possible bug? or I have to force a non external window?

**Comment by EgorBo** [comment]
@Jaroost acording to Urho3D C++ sources, multisampling could be set only in case if ExternalWindow is null (see OGLGraphics.cpp)
You may try to set multisampling directly in Texture2D (see SetSize for example)
or enable FXAA
viewPort.RenderPath.Append(CoreAssets.PostProcess.FXAA2); //or FXAA3

**Comment by EgorBo** [comment]
Also, I've just added Multisampling property to ApplicationOptions (it uses "-m")

**Comment by Jaroost** [comment]
> acording to Urho3D C++ sources, multisampling could be set only in case if ExternalWindow is null (see OGLGraphics.cpp)

Oops sorry my mistake.

Problem is there is no texture, only materials.

By the way I close this issue.
