### ISSUE TITLE
BufferedSoundStream can't play PCM uncompressed audio files

### ISSUE THREAD

**Issue by rnikitin** [xamarin/urho#201]
I'm making an app for my drum classes and to make it cross-platform I've chosen Urho.Sharp, because it has low level Sound API as well as rich graphics capabilities.  As a first step I'm making a metronome app and for that I'm working with BufferedSoundStream adding here audio and then needed silence, as described here: https://github.com/xamarin/urho-samples/blob/master/FeatureSamples/Core/29_SoundSynthesis/SoundSynthesis.cs.  
But the resulting sound is not sound at all, like random bits got into a sound stream, but source files are PCM audio without any encoding and they are playing well with SoundSource.  Do you have any ideas why it doesn't play from BufferedSoundStream?

This is my code:

``` csharp
///
/// this code initialize sound subsystem
///
void CreateSound()
{
    // Sound source needs a node so that it is considered enabled
    node = new Node();
    SoundSource source = node.CreateComponent<SoundSource>();

    soundStream = new BufferedSoundStream();
    // Set format: 44100 Hz, sixteen bit, stereo
    soundStream.SetFormat(44100, true, true);

    // Start playback. We don't have data in the stream yet, but the 
    SoundSource will wait until there is data,
       // as the stream is by default in the "don't stop at end" mode
       source.Play(soundStream);
}

///
/// this code preload all sound resources
///
readonly Dictionary<PointSoundType, string> SoundsMapping = new Dictionary<PointSoundType, string>
    {
        {PointSoundType.beat, "wav/beat.wav"},
        {PointSoundType.click, "wav/click.wav"},
        {PointSoundType.click_accent, "wav/click_accent.wav"},
        {PointSoundType.crash, "wav/crash.wav"},
        {PointSoundType.foot_hh, "wav/foot_hh.wav"},
        {PointSoundType.hh, "wav/hh.wav"},
        {PointSoundType.open_hh, "wav/open_hh.wav"},
        {PointSoundType.ride, "wav/ride.wav"},
        {PointSoundType.snare, "wav/snare.wav"},
        {PointSoundType.tom_1, "wav/tom_1.wav"},
        {PointSoundType.tom_2, "wav/tom_2.wav"},
    };

Dictionary<PointSoundType, Sound> SoundCache = new Dictionary<PointSoundType, Sound>();

private void LoadSoundResources()
{
    // preload all sounds
    foreach (var s in SoundsMapping)
    {
        SoundCache[s.Key] = ResourceCache.GetSound(s.Value);
        Debug.WriteLine("resource loaded: " + s.Value + ", length = " + SoundCache[s.Key].Length);
    }
}

///
/// this code fill up the stream with audio
///
private void UpdateSound()
{
    // Try to keep 1/10 seconds of sound in the buffer, to avoid both dropouts and unnecessary latency
    //float targetLength = 1.0f / 10.0f;

    // temporary increase buffer to 1s
    float targetLength = 1.0f;

    float requiredLength = targetLength - soundStream.BufferLength;
    if (requiredLength < 0.0f)
        return;

    uint numSamples = (uint)(soundStream.Frequency * requiredLength);

    // check if stream is still full
    if (numSamples == 0)
        return;

    var silencePause = new short[44100];

    // iterate and play all sounds 
    SoundCache.All(s =>
    {
        soundStream.AddData(s.Value.Handle, s.Value.DataSize);

           // add silencio
           soundStream.AddData(silencePause, 0, silencePause.Length);

        return true;
    });
}
```

**Comment by EgorBo** [comment]
@rnikitin Could you please attach a complete repro project with the wav files you mentioned in the code?
As far as I can see you provide a Sound object pointer to AddData that expects a pointer to sound data (bytes)

**Comment by rnikitin** [comment]
@EgorBo no I haven't tried Urho3D because of lack of C++ skills...

But you pointed to a good idea. So instead of getting ```Sound``` I'm trying to get ```File``` using ```ResourceCache.GetSound()``` method to read it byte content:
``` csharp
var file = ResourceCache.GetFile(s.Value, true);
var size = file.Size;
```

To use later ```File.Read()``` to read it content into byte array. 

But if I run it in IO thread, I'm getting ```An unhandled exception occured.``` and if inside ```Task.Run``` - it's just silently fails. 
After some more investigations I found that file reads well but the problem is with ```Size``` getter, which is defined in the extension class here - [File.cs](https://github.com/xamarin/urho/blob/master/Bindings/Portable/File.cs)

Without ```file.Size``` I can't call ```File.Read``` and make correct size for byte array.

Could it be a problem with ```File_GetSize``` method?

**Comment by rnikitin** [comment]
This is solution file:
[UrhoDrums - Copy.zip](https://github.com/xamarin/urho/files/914991/UrhoDrums.-.Copy.zip)

Check ```AudioMixerPage.cs``` and ```UrhoApps/AudioMixerApp.cs``` files.
