### ISSUE TITLE
error install Urhosharp1.3.0

### ISSUE THREAD

**Issue by shao200** [xamarin/urho#204]
无法安装程序包“UrhoSharp 1.3.0”。你正在尝试将此程序包安装到目标为“.NETPortable,Version=v4.5,Profile=Profile259”的项目中，但该程序包不包含任何与该框架兼容的程序集引用或内容文件。有关详细信息，请联系程序包作者。		china

**Comment by EgorBo** [comment]
UrhoSharp uses Profile111 for PCL, so it complains on Profile259.
