### ISSUE TITLE
Rename *HoloLens* classes, namespaces and file names to MixedReality

### ISSUE THREAD

**Issue by vladkol** [xamarin/urho#206]
Platform grew across different devices (HoloLens, PC) and experiences (AR/VR/Mixed Reality). The umbrella term is Mixed Reality, so it makes sense to rename classes, namespaces and files.

**Comment by migueldeicaza** [comment]
While we can rename, we need to find a name that is strongly associated with the Windows stack.

MixedReality is confusing, because it is a term that predates this internal rebranding and in use in the industry.   It would confuse android and iOS users to find that "MixedRealty" is windows-only.

**Comment by vladkol** [comment]
Fair. 
But HoloLens is confusing too, people may thing Urho is HoloLens-only. As an alternative, you may introduce MixedReality namespace branching it to MixedReality.Windows, MixedReality.GoogleDream, MixedReality.Oculus, MixedReality.OpenVR, etc. 
As a developer, I'd love to have a set of device-agnostic classes for VR app, HMD-driven camera, and controllers/hands. Everything else goes under vendor-specific namespaces.

**Comment by EgorBo** [comment]
@vladkol @migueldeicaza How about UrhoSharp.MixedReality.Windows ? Quite long but it's not confusing :) 
@vladkol all basic/abstract stuff is available in PCL, even **HoloApplication** class and thus it can be used even in Android + Google Cardboard apps

**Comment by migueldeicaza** [comment]
Let us leave MixedReality entirely out of it.

I am open to ideas in a new realm.

**Comment by vladkol** [comment]
Well, Unity folks went straight with VR, even though it includes AR and MR support too. 
Introducing new realms may be even more confusing.

**Comment by migueldeicaza** [comment]
I am in no rush to make the change, we can wait until the right name comes.  In the meantime, I'll discuss with Egor offline.   Keeping the issue open hoping that someone can shed some better light.

**Comment by migueldeicaza** [comment]
Ok, we came up with names.

`StereoApplication` replaces `HoloApplication`, and `SharpReality` is the general namespace for apps that are used in the space.

**Comment by vladkol** [comment]
Mono -> Stereo 👍 Love it!

**Comment by vpenades** [comment]
Is there any support of Urho3D to Cardboard/Daydream ?
