### ISSUE TITLE
Crash after attempting to display an UrhoSharp ContentPage for the 2nd time in UWP

### ISSUE THREAD

**Issue by vpenades** [xamarin/urho#210]
I have a cross platform application with a root NavigationPage and several child ContentPage(s) , some of them enhanced with UrhoSharp UrhoSurface.

Upon first navigation to a ContentPage with Urho content, everything works fine, but if I try to navigate to another Urho enhanced content page, I get this exception:

`Could not create window, root cause: 'WinRT only supports one window'. You can omit this exception by subscribing to Urho.Application.UnhandledException event and set Handled property to True.`

We tried to omit the exception, but then the application just freezes.

[More people having the same issue here](https://forums.xamarin.com/discussion/94387/xamarin-forms-urhosharp-1-4-4-uwp-the-second-execution-i-get)

In Android, navigation works fine

Using
- UrhoSharp.Forms 1.4.18
- Xamarin.Forms 2.3.4.231

We urgently require this to be fixed and we do require page navigation so on each page OnAppearing/OnDisappearing we can create/destroy the UrhoSurface instance correctly.

**Comment by EgorBo** [comment]
@vpenades Sorry for the delayed response, the issue should be fixed now in master.

**Comment by jkalexander** [comment]
Having the same issue (exact same error) using UrhoSharp.Forms 1.9.67 and Xamarin.Forms 3.4.0.1008975.
Things work fine in WPF though, issue is specific to UWP

**Comment by JayGodiz** [comment]
Mine Crashes when I first open the App and this only happens on IPhoneX but runs ok on others
