### ISSUE TITLE
UrhoSurface.CreateSurface Error

### ISSUE THREAD

**Issue by Zamir7** [xamarin/urho#213]
In Android mode VS 2017 writes
`Error CS0308 The non-universal method "UrhoSurface.CreateSurface (Activity)" can not be used with arguments of type`
(on last versions, after 1.3)

**Comment by LanceJZ** [comment]
How is that a false alarm? How did you fix it? I'm having the same issue.
Also AbsoluteLayout() is obsolete.

**Comment by andrewbenson-92** [comment]
change it to 
`var surface = UrhoSurface.CreateSurface(this)`
