### ISSUE TITLE
System.InvalidOperationException when using Button.Released += ...

### ISSUE THREAD

**Issue by elv1s42** [xamarin/urho#214]
Hi!

I was using extension method for adding action on released event:
``` csharp
public static Button WithAction(this Button b, Action a)
{
    b.SubscribeToReleased(args => { a.Invoke(); });
    return b;
}
```
But with the latest version this `SubscribeToReleased` method was marked as obsolete, so I started using `Released` like so:
``` csharp
public static Button WithAction(this Button b, Action a)
{
    b.Released += args => { a.Invoke(); };
    return b;
}
```
With this new approach I started getting System.InvalidOperationException:
![sceen1](https://cloud.githubusercontent.com/assets/6689884/25912236/3d482ad6-35bf-11e7-99bb-40b9bad233e9.png)

```   
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Urho.UrhoEventAdapter`1.<>c__DisplayClass3_0.<AddManagedSubscriber>b__0(TEventArgs args)
   at Urho.Gui.Button.<>c__DisplayClass77_0.<SubscribeToReleased>b__0(IntPtr x)
   at Urho.UrhoObject.ObjectCallback(IntPtr data, Int32 stringHash, IntPtr variantMap)
   at Urho.Application.Application_Run(IntPtr handle)
   at MyApp.Desktop.Program.Main(String[] args) in C:\Users\...\MyApp\Desktop\Program.cs:line 10 
```

I am using v1.4.38:
![screen2](https://cloud.githubusercontent.com/assets/6689884/25912294/69277e90-35bf-11e7-95dc-8017fceb6ec6.png)

This extension method is used only once while creating new button.
Is it an issue/bug or using extension method is not correct for this case?

**Comment by EgorBo** [comment]
@elv1s42  looks like you tried to subscribe to Released event in a Released event handler 
`b.Released += e => b2.Released += ...`
and this caused the issue. (or you tried to subscribe from a different thread) I am fixing it now.

**Comment by elv1s42** [comment]
Ok, I just expected that both old and new methods will work the same way.
Thank you @EgorBo

**Comment by elv1s42** [comment]
Hi, I've checked it and can confirm that using 
`b.Released += args => { a.Invoke(); };` 
instead of 
`b.SubscribeToReleased(args => { a.Invoke(); });` is safe now (in v1.4.47).

@EgorBo, thank you for quick fix!
