### ISSUE TITLE
StaticModel - discard/cut off the parts of Model

### ISSUE THREAD

**Issue by MichalPetryk** [xamarin/urho#215]
Is there any way to discard/cut off parts of Model (loaded from *.mdl file), which conflicts with another Model loaded from *.mdl file?

**Comment by EgorBo** [comment]
sounds like a job for shaders (glsl/hlsl) and doesn't relate to C# bindings, I'd recommend to ask such questions on the urho3d forum: https://discourse.urho3d.io/
