### ISSUE TITLE
UWP TakeScreenshot returns black image

### ISSUE THREAD

**Issue by daniel-packard** [xamarin/urho#220]
Tracking an issue noted by @kylecolden (and others) in the Xamarin forums: https://forums.xamarin.com/discussion/comment/280393/#Comment_280393

> June 14
I'm seeing the Black image from TakeScreenshot using UWP. It doesn't matter whether I capture it in OnTouchEnd, from my xamarin forms button, whether I invoke to main in my urho app or not. It always comes back as a black image. Tried all the different Save, SavePNG, SaveJPG, etc methods.
@DMcLennan or anyone else able to get TakeScreenshot working (hopefully on UWP)?

**Comment by daniel-packard** [comment]
Hi @EgorBo -- just verified this is still an issue in 1.7.3-pre, I'm going to dig in and see if I can't at least identify the cause.

**Comment by dotMorten** [comment]
This is a known limitation of the UWP SwapChainPanel. It just can't do it. It isn't a bug in Urho.

The Bing Maps control actually got some secret internal hook to pull it off, but sadly the same is not exposed to us external developers.

**Comment by daniel-packard** [comment]
Hey @dotMorten - thanks for the response!

I just want to make sure your comments would apply in our case -- we are calling `Urho.Application.Graphics.TakeScreenshot(Image dest)`, and I can't see where that would hit Xaml.RenderTargetBitmap() directly, although it looks like it _does_ hit the swapchainpanel in the native urho D3D implementation.

As far as I can see, TakeScreenshot should 

1. Pass through the generated binding: https://github.com/xamarin/urho/blob/3aa1039af54f465c2ece887c80cd278185eec735/Bindings/Portable/Generated/Graphics.cs#L249-L259
2. which I'm _thinking_ would pass it to the D3D Urho implementation: https://github.com/urho3d/Urho3D/blob/70049ba58210ad26d8402363cf4d864f6c294155/Source/Urho3D/Graphics/Direct3D11/D3D11Graphics.cpp#L492-L570

That is probably hitting the swapchainpanel through the native implementation at some point.. but are you sure the limitations noted on RenderTargetBitmap would apply in this case? (I really don't know, just don't want to give up prematurely)

Even if your comments do apply, there is some hope through the comments on this Q&A: 
https://code.msdn.microsoft.com/vstudio/XAML-SwapChainPanel-00cb688b/view/Discussions/2

> Unfortunately, RenderTargetBitmap does not capture the contents of a SwapChainPanel. However, you can use the same rendering code provided in the sample to draw the same content to a SurfaceImageSource, and then use RenderTargetBitmap to capture that if you'd like.

What do you think?

**Comment by dotMorten** [comment]
Aaah my bad! Yeah you can totally do a read-back (I do that in my own DirectX stuff too as a workaround for RTB). Sorry I assumed the screenshot method was using RTB, when there was actually a proper native method made for it.

**Comment by daniel-packard** [comment]
So you're saying there's hope 😄  I will continue my effort then. 

Thanks for your comments and links!

**Comment by patrickabadi** [comment]
@dotMorten would you be able to share the code you use to do the read-back from swapchain to surfaceimagesource.  I'm looking to implement a work-around to be able to save a screenshot.  If you want you could send it to me privately.

Thanks!

**Comment by dotMorten** [comment]
@patrickabadi Sorry no. it's in a part of the code I didn't write (ie don't understand) and has several layers of custom abstraction for cross platform support.
