### ISSUE TITLE
Can't override UIElement.Update

### ISSUE THREAD

**Issue by iainmerrick** [xamarin/urho#221]
In the C++ interface, UIElement has a `virtual Update(float timeStep)` method. Subclasses can override this to hook into the update event.

In the C# wrapper, it looks like I can't override this. The method exists, and by default it calls through to `UIElement::Update` on the C++ side (which does nothing). But if I write a subclass of UIElement in C#, its Update method doesn't override the C++ method.

Impact: the C++ library calls Update() on all UI elements every frame, but this mechanism is completely inaccessible to C#.

Same thing probably applies to a bunch of other virtual methods in UIElement: OnClickBegin, OnWheel, OnKey, OnResize, etc.

The C# method is marked `virtual`, so I figure it's _meant_ to be overridden, it just isn't hooked up to the C++ class properly. To fix this, I guess the C# bindings would have to use some private "UIElementStub" class, which overrides `UIElement::Update` to call through to the C# method.

**Comment by iainmerrick** [comment]
I'm happy to try fixing this! But I could use a couple of pointers first:

- Is my assessment correct?
- Are there other classes where we've implemented this kind of thing? (If so I'll copy their approach)

**Comment by iainmerrick** [comment]
Same thing probably applies to a bunch of other virtual methods in UIElement: OnClickBegin, OnWheel, OnKey, OnResize, etc.

**Comment by iainmerrick** [comment]
The `Application.Start` method is hooked up correctly. This is done via an `ApplicationProxy` class on the C++ side. So I think we need a similar `UIElementProxy` class to connect all the UIElement hooks.

**Comment by migueldeicaza** [comment]
Your analysis is correct on what is required.

We already provided such `UIElementProxy`, it just has a different name, you are looking for  `UserComponent`.

**Comment by iainmerrick** [comment]
Did you mean to close this? What about the bug?

**Comment by EgorBo** [comment]
@iainmerrick  it's not really a bug - most of the C++ callback are surfaced to C# via events - our bindings don't support virtual methods - for most cases events are enough.For all methods you mentioned you can find a corresponding event.
