### ISSUE TITLE
Transparent background?

### ISSUE THREAD

**Issue by lucabee** [xamarin/urho#224]
Is possible to set Transparent color as background scene?
I create a scene and Octree component.
I'm able to set different color by SetClearColor of Viewport, but it does not work with transparent color.
I think it could be a powerful and useful feature for showing ed component over xamarin views
Thank for help

**Comment by EgorBo** [comment]
@lucabee 
you probably can "take a screenshot" of your UI and use it as a background texture each frame but I am not sure UIGraphicsGetImageFromCurrentImageContext will work fast enough.
You can check my ARKit sample to see how to render custom texture as a background - https://github.com/EgorBo/ARKitXamarinDemo

**Comment by IssacKramer** [comment]
@EgorBo 
HI Egor.
I ask from you to Reopen this issue because of its importance to Xamarin forms developers!
I opened a new issue for it [#271](https://github.com/xamarin/urho/issues/271), so if you can upgrade it's priority it would be great.
**Thank you very much for you work!**
Issac
