### ISSUE TITLE
UI Default Style

### ISSUE THREAD

**Issue by Fanvaron** [xamarin/urho#227]
Hello,
I just updaten my projekt from 1.0.56 to the newest Version.
Now I have the Problem that my UI Elements (Buttons and Dropdown) are blue instead of the white they were before. After some testing it seems that the DefaultStyle.xml and the used UI.png do not seem to work properly. It seems like he does not use the png at all.
Here the (hopefully) relevant Code snippets:
``public C_Display(ApplicationOptions opt) : base(new ApplicationOptions(assetsFolder: "Data")) { }``

`` XmlFile Loc_Style = ResourceCache.GetXmlFile("UI/DefaultStyle.xml");``
``UI.Root.SetDefaultStyle(Loc_Style); ``

DefaultStyle.xml:
`` <element type="BorderImage" >``
``        <attribute name="Texture" value="Texture2D;Textures/UI.png" />``
``        <attribute name="Blend Mode" value="alpha" />``
``    </element>``
``    <element type="Button" style="BorderImage">``
``        <attribute name="Image Rect" value="16 0 32 16" />``
``        <attribute name="Border" value="4 4 4 4" />``
``        <attribute name="Pressed Image Offset" value="16 0" />``
``        <attribute name="Hover Image Offset" value="0 16" />``
``        <attribute name="Pressed Child Offset" value="-1 1" />``
``    </element>``

![unbenannt](https://user-images.githubusercontent.com/5766194/29019180-1f0fe042-7b5e-11e7-8c25-59fbf56166e1.PNG)

It worked just like this in Version 1.0.56 but newer versions don't seem to accept this anymore.
I already went through the example code and I could not find any indication that something changed.
Sincerely
Marvin

**Comment by EgorBo** [comment]
@Fanvaron 
most likely because UI.png and DefaultStyles.xml are parts of CoreData now - try to rename them in your project and your code.

**Comment by Fanvaron** [comment]
You are right, it was that easy. 
Thank you very much!
