### ISSUE TITLE
Load custom model on iOS

### ISSUE THREAD

**Issue by lucabee** [xamarin/urho#230]
I have Xamarin.Forms solution.
I want to load mdl model from local storage.

I wrote this code that works only for Android
`StaticModel modelObject = node.CreateComponent<StaticModel>();
string localMdl = Path.Combine(PCLStorage.FileSystem.Current.LocalStorage.Path, "bucket.mdl");
modelObject.Model = ResourceCache.GetModel(localMdl);`

Is there a way to make it works also on iOS?

**Comment by EgorBo** [comment]
@lucabee 
You have to store assets in the iOS project, not in PCL if you do

Example:
1) file must be under "Resource\[any name]" folder, for example: MyiOSProject/Resources/MyData/MyModels/bucket.mdl
with "BundleResource" build action (see file properties)
2) your should use "MyData" in you applicationOptions object (new ApplicationOptions("MyData"))
3)  modelObject.Model = ResourceCache.GetModel("MyModels/bucket.mdl");

**Comment by lucabee** [comment]
@EgorBo 
Thanks for your reply but my problem is different.
I am able to load mdl model from assets, both Android and iOS and everything works perfect.
I have opened the issue because I want load dynamically mdl files.
Example:
1. download .mdl file from web
2. store .mdl file into LocalStorage 
3. load Model from LocalStorage

Now it works on Android but not on iOS
Thanks

**Comment by EgorBo** [comment]
@lucabee 
iOS expects assets to be "BundleResource"
but you can try to load your model to bytes via System.IO.File
and then load to Model:

	Model model = new Model();
	model.Load(new MemoryBuffer(File.ReadAllBytes(file)));

**Comment by pradeepkumarca** [comment]
Did you got the solution for this. I am also trying for the similar kind of scenario. Where in I need to store .mdl/.xml files in local mobile folder and need to read it when the application opens.

Thanks in advance :)

**Comment by akema-trebla** [comment]
Did any of you find a solution for iOS? Kindly let me know.
