### ISSUE TITLE
Urho3D 1.7 is out and it support 64bits for Windows

### ISSUE THREAD

**Issue by JimSEOW** [xamarin/urho#234]
I wonder if there is a plan now to bring UrhoSharp to support 64bit in Windows?

IS this new release makes it more feasible to build for ARM for W10M and the upcoming W10A (Win On ARM)?

**Comment by stark7** [comment]
I am hoping we can get an urhosharp that reflects the current Urho3D master for it also comes with 3D UI elems. Is there a way to know the release schedule for the urhosharp updated nuget packages?

**Comment by EgorBo** [comment]
@JimSEOW @stark7 I hope I'll be able to release it soon
I am updating it right now - lots of conflicts.

**Comment by stark7** [comment]
Thanks EgorBo! I am super excited to see that 3D UI in action.

**Comment by stark7** [comment]
Hey @EgorBo - how's it going? 😸 Is 1.7 doing good? You're like GRRM writing A Game of Urho - some are dying to get it hehe.

**Comment by EgorBo** [comment]
1.8 is released 🙂
