### ISSUE TITLE
How to run urhosharp without worker threads?

### ISSUE THREAD

**Issue by MichalPetryk** [xamarin/urho#235]
Hi,
Is there any way to run urhosharp without worker threads? In Urho3D we can do it by setting:
<pre>engineParameters[EP_WORKER_THREADS] = false</pre>

**Comment by EgorBo** [comment]
@MichalPetryk you can use command line arguments 
`new ApplicationOptions("MyData") { AdditionalArguments = " -nothreads" };`
see https://urho3d.github.io/documentation/1.7/_running.html

**Comment by MichalPetryk** [comment]
@EgorBo thank you!

PS: Property name is AdditionalFlags instead of AdditionalArguments ;)
