### ISSUE TITLE
Quaternion.FromEulerAngles

### ISSUE THREAD

**Issue by stark7** [xamarin/urho#242]
Quaternion.FromEulerAngles is missing.

I will also turn this into a pull request soon if nobody else gets to it first.

**Comment by EgorBo** [comment]
@stark7 there is a constructor that accepts euler angles - `new Quaternion(x: 0, y: 90, z: 0);`

**Comment by stark7** [comment]
Thanks Egor - I just noticed the comment above the constructor :).
