### ISSUE TITLE
Need to show a warning on Desktop if running on 32 bits

### ISSUE THREAD

**Issue by eafreak** [xamarin/urho#249]
Hallo

I want to try out Urho for WPF, however, I noticed the samples has a reference to Urho.Desktop.dll which I cannot seem to find on Nuget. There is an Extensions.Wpf but I cannot seem to get it to work.

Thanks

**Comment by eafreak** [comment]
I am not sure if this is intended.. But it seems Urho.Desktop is not needed.

The main problem is that I had Any CPU as platform target, when I changed to x64 I got it to work.

**Comment by migueldeicaza** [comment]
We should show a warning on desktop if we run in 32 bit mode to indicate to the user that they need to run 64.

**Comment by EgorBo** [comment]
we had such a warning, the Workbooks guys asked me to remove it 🙂

**Comment by EgorBo** [comment]
Fixed by https://github.com/xamarin/urho/commit/30b9e6d36b27d75e30fcbb87d6a5b8c366e18b01
