### ISSUE TITLE
Bindings API Coverage

### ISSUE THREAD

**Issue by Alan-FGR** [xamarin/urho#258]
Hello there.

Is there any information either collected or maybe an estimation/guess on the overall coverage of the bindings? I noticed that some API that's available in Urho/AS isn't present in UrhoSharp, for example 2D physics queries. While it's true that Urho is a bit lacking in that regard (no shape test or TOI), it does have say raycasting what I couldn't find in UrhoSharp.

I understand that automated binders only go so far, and funnily enough apparently the same things that are lacking in UrhoSharp are the things we had to manually bind in Atomic (I'm a contributor there), but if there's information on what's missing, that would be valuable not only for contributions but also to have an idea on the overall usability of UrhoSharp.

Please let me know if I'm missing something (what's a real possibility), and thanks in advance.

**Comment by migueldeicaza** [comment]
There is no tool that shows this.

You can either do a manual audit of the APIs, or look at the output of the binding generator which in some cases outputs some skipped methods, and finally look at the source code for the generator to spot things that the generator skips.

**Comment by Alan-FGR** [comment]
@migueldeicaza thank you. Skipped methods should provide a good resource to estimate that.

**Comment by EgorBo** [comment]
@Alan-FGR could you please list all missing methods you need?

**Comment by Alan-FGR** [comment]
@EgorBo sure! Just give me a few days because I'm quite busy at the moment. Off the top of my head I can name a few in the PhysicsWorld2D:

- GetRigidBodies
- RayCast
- RayCastSingle

I guess the ones that return collections won't be straightforward to fix. I did fix the raycasting in Atomic but the signatures aren't the same as Urho (because 2D and 3D physics calls in Urho are quite different, and we wanted to keep them consistent in Atomic), so I don't think the code will be of much use to you.

**Comment by Alan-FGR** [comment]
Hi guys. I'm sorry but I'm not planning to touch this anytime soon, I should've taken note of the other missing stuff I found when using UrhoSharp. This project is still on my radar and I hope you guys keep up the good work! I wish I had the time to contribute... unfortunately as a freelancer you don't get to pick the tech you use and putting some substantial effort on this isn't currently justifiable for me.

**Comment by Alan-FGR** [comment]
I'm going to give UrhoSharp a try once again. I'm going to port a C++ project and this time I'll write down any API holes I might encounter. Should I open separate issues for each of them as I find or make a single issue? I might also fix some of them.
P.S.: PhysicsWorld.GetRigidBodies is another missing method... since RigidBody is marshaled elsewhere I wonder what would be require to marshal a PODVector<RigidBody>

**Comment by migueldeicaza** [comment]
Would love if you could open separate issues with the problems that you face, that way we can track those individually.

We know that `PODVector<X>` is an issue, we should track the binding of `PODVector<X>` as a separate issue as well.

**Comment by Alan-FGR** [comment]
@migueldeicaza OK, I will. In fact for some of them I could fix and submit a PR instead, however, I see some repetitive code in the native wrapper for the functions returning PODVectors:
https://github.com/xamarin/urho/blob/f38c3aea1f3804c7166b88f59900b5ff73d4a996/Bindings/Native/glue.cpp#L300-L309
https://github.com/xamarin/urho/blob/f38c3aea1f3804c7166b88f59900b5ff73d4a996/Bindings/Native/glue.cpp#L315-L324
https://github.com/xamarin/urho/blob/f38c3aea1f3804c7166b88f59900b5ff73d4a996/Bindings/Native/glue.cpp#L330-L340
Maybe that could be addressed to make it easier/simpler to manually wrap that way, although I'm not sure if you guys are planning to tackle that from the generator (making it generate that kind of code).
In any case, in the mean time it's no problem of course to just copy and paste that "template".
