### ISSUE TITLE
[v1.7.3-pre] MissingMethodException being thrown on UWP

### ISSUE THREAD

**Issue by FlammableFork** [xamarin/urho#261]
On UWP, the following MissingMethodExceptions are being thrown:

`System.MissingMethodException: Method not found: 'Boolean Urho.Gui.Text.SetFont(Urho.Gui.Font, Single)'.`
`System.MissingMethodException: Method not found: 'Urho.Node Urho.Node.CreateChild(System.String, Urho.CreateMode, UInt32, Boolean)'.`

I have tested this in my own app as well as the FormsSample app (after adding a UWP project) and these exceptions are being thrown in both apps. UWP is the only platform affected while version 1.7.3-pre appears to be the only affected version.  Versions 1.7.0-pre and earlier work properly.

**Comment by marcojak** [comment]
Same here,
I'm wondering if this project is still active or not.
A word from Xamarin would be great

**Comment by EgorBo** [comment]
Fixed in 1.8.x.
