### ISSUE TITLE
Error  Android Xamarin listview outofmemory

### ISSUE THREAD

**Issue by MiguelPatino06** [xamarin/urho#262]
Hi People, I have the following error in my listview after doing some operation, this happens to the fourth or fifth process or event

Output
Alloc concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 511MB/512MB, paused 1.041ms total 70.412ms

**Comment by FlammableFork** [comment]
Hi @MiguelPatino06,

This issue tracker is specifically for UrhoSharp, so you are not likely to receive much help with your issue using the ListView.

If you would like to submit a bug to Xamarin, it would be best to do so here: [https://bugzilla.xamarin.com/newbug](https://bugzilla.xamarin.com/newbug)

If, however, you are more interested in getting some help with your issue and not submitting a bug, using the forums would probably yield better responses ([https://forums.xamarin.com](https://forums.xamarin.com)).  I wish you the best of luck.
