### ISSUE TITLE
StringHash doesn't implement equality operators

### ISSUE THREAD

**Issue by gleblebedev** [xamarin/urho#272]
StringHash doesn't implement equality operators so one can't simply compare StringHash values :)

**Comment by EgorBo** [comment]
Does it need ones?
It is a struct with a value-type 4-bytes field. It means it uses a "fast" GetHashCode/Equals implementation that takes the "Code" field into account.

```
var a1 = new StringHash(123);
var a2 = new StringHash(123);
var eq1 = a1.Eqauls(a2);
var eq2 = a1.GetHashCode().Eqauls(a2.GetHashCode());
```

both are true.

**Comment by gleblebedev** [comment]
Can you write  "a1 == a2"?

**Comment by EgorBo** [comment]
@gleblebedev got it, added :)
