### ISSUE TITLE
How to disable Backface culling?

### ISSUE THREAD

**Issue by EduardsBrown** [xamarin/urho#274]
Hi,

I am trying to render buildings, using OSM data the points come in clockwise and anticlockwise order so it's very hard to render buildings consistently. How can I disable culling?

I found:
`this.Renderer.SetCullMode(CullMode.None, this.CullingCamera);`
`this.Graphics.CullMode = CullMode.None;`

But that doesn't change it for some reason, I suspect this needs to be called somewhere before the main rendering happens, so I overridden:
`this.Engine.RenderUpdate += Engine_RenderUpdate;`
`this.Renderer.BeginViewRender += Renderer_BeginViewRender;`

None of them worked.
I am a bit stuck, any help would be appreciated. 

Thank you.
Ed.

**Comment by EduardsBrown** [comment]
Resolved after finding this post:
https://discourse.urho3d.io/t/solved-render-two-faces-of-plane-and-ignore-shadows/1827

This lead me to find CullMode setting under Model.Material.CullMode. :)

**Comment by EgorBo** [comment]
Not sure what Graphics.CullMode does but I suspect it will affect only "new" materials. So yes it is better to change culling mode directly in the material.
