### ISSUE TITLE
UWP Release and x64 support

### ISSUE THREAD

**Issue by patrickabadi** [xamarin/urho#275]
I'm trying to get 64bit builds working in UWP.

At first I tried using the existing mono-urho.uwp project but found it was using a pre-built SdlStub lib first which didn't include the source.  I tried building my own SDL lib based on 2.0.4 code but ran into several issues along the way.

Another avenue I tried was getting the UrhoSharp.SharpReality project built and running for UWP as they are mostly the same platform.  I was able to get the project built properly and linking for x86 and x64.  The problem I have now is when starting the test app I get a 

```
System.AccessViolationException.

   at Urho.Application.Application_Run(IntPtr handle)
   at Urho.Application.Run()
   at Urho.UWP.UrhoSurface.Run(Type appType, ApplicationOptions options)
   at Urho.UWP.UrhoSurface.Run[TGame](ApplicationOptions options)
   at Playgrounds.UWP.MainPage.<MainPage_Loaded>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Playgrounds.UWP.MainPage.MainPage_Loaded(Object sender, RoutedEventArgs e)
```

Is there anyone out there that would be able to help point me in the right direction?  Our company is invested in Urho's solution and we need to be able to properly support UWP x64.

**Comment by patrickabadi** [comment]
I've managed to work around this and I have a working x64 Release UWP build.  I'm not sure who is looking after this repository, but I would love to include my changes so others could benefit from this work.

**Comment by daniel-packard** [comment]
Hi @EgorBo or @migueldeicaza  - Can you please provide an update on the status/priority of UWP support for Urho in release mode and/or 64bit?

We (mostly @patrickabadi) made some good progress towards 64-bit release support on a branch in our fork of the project: 
- https://github.com/complexrehabsystems/urho/tree/crs-Add_UWP_Support

... but we understand that getting such a large pull request accepted upstream by you might be challenging, and we don't want to become far separated from the official packages/repo. If there is a way that we can coordinate/contribute more effectively, we'd love to help out!

**Comment by daniel-packard** [comment]
@EgorBo, @migueldeicaza - ping. Just trying to understand how Urho/UWP fits into the grand scheme of Microsoft/Xamarin's priorities so we can decide how to proceed on our project.

Is there a better way for me to reach out?

Thanks guys!

**Comment by EgorBo** [comment]
@daniel-packard sorry for the delay, 
Still working on it, there are a few more important tasks but I hope I'll deliver the fixed SDL implementation for UWP next week

**Comment by daniel-packard** [comment]
Hey, thanks @EgorBo -- Sounds like great news!

Please let us know if there's a better way for us to coordinate in the future. We (i.e. patrick) had made significant progress towards a working UWP 64 bit release build, and we'd love for that effort to help out upstream.

**Comment by EgorBo** [comment]
Fixed in master

**Comment by daniel-packard** [comment]
@EgorBo -- thanks so much! This unblocks some significant items for our application 💯 

We are going to checkout and start testing tomorrow
