### ISSUE TITLE
UWP native library isn't following the 'nuget' way of deploying runtimes

### ISSUE THREAD

**Issue by dotMorten** [xamarin/urho#277]
Currently a .targets file is used to deploy the Urho native dll in UWP: https://github.com/xamarin/urho/blob/master/Nuget/UWP/UrhoSharp.targets

There's a much simpler way to do this by placing the native libs in the following folders, negating the need for the .targets file:
 - `\runtimes\win10-x86\native\mono-urho.dll`   (x86 dll)
 - `\runtimes\win10-x64\native\mono-urho.dll`   (x64 dll)
 - `\runtimes\win10-arm\native\mono-urho.dll`   (ARM dll if it ever gets created)

This is documented some-what here: https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages

**Comment by migueldeicaza** [comment]
Thanks for the guidance!
