### ISSUE TITLE
window icon & HiDPI on windows?

### ISSUE THREAD

**Issue by qntf** [xamarin/urho#279]
how can i set a custom window icon on desktop targets?
Also, how can I enable HiDPI on Windows?

**Comment by EgorBo** [comment]
The icon can be chaged using the following code:
```
Image img = new Image();
img.LoadFile(@"C:\Users\bogat\myIcon.png");
Graphics.SetWindowIcon(img);
```
No idea regarding the HiDPI mode for Windows (it does work for macOS). Probably needs to be asked on Urho3D forum
