### ISSUE TITLE
Missing binding for Vector2.CalculateAngle

### ISSUE THREAD

**Issue by andrekoehler** [xamarin/urho#281]
Vector3.CalculateAngle exists, but Vector2.CalculateAngle does not.

https://github.com/xamarin/urho/blob/db5206bbb8e4c293ce9e2ea01b7e59a272fc235d/Bindings/Portable/External/Vector3.cs#L1143

https://github.com/xamarin/urho/blob/db5206bbb8e4c293ce9e2ea01b7e59a272fc235d/Bindings/Portable/External/Vector2.cs

**Comment by migueldeicaza** [comment]
Merged
