### ISSUE TITLE
Packaging - BadImageFormatException when running in 32 Bit mode

### ISSUE THREAD

**Issue by andrekoehler** [xamarin/urho#291]
I get a
> System.BadImageFormatException
>   HResult=0x8007000B
>   Message=An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
>   Source=Urho
>   StackTrace:
>    at Urho.Context.Context_Context()
>    at Urho.Context..ctor()
>    at Urho.Application..ctor(ApplicationOptions options)
>    at the first line of my code that uses Urho

This only occurs when running with the x86 build or the AnyCPU+Prefer32 build.

The reason for this lies in here:
https://github.com/xamarin/urho/blob/db5206bbb8e4c293ce9e2ea01b7e59a272fc235d/Nuget/Desktop/UrhoSharp.targets#L7-L14

And the Platform Invoke code uses a compile time constant instead of deciding the name of the DLL at runtime:
https://github.com/xamarin/urho/blob/426eb85782b4124ed9a42a8336bafbb0750f1bc0/Bindings/Portable/Consts.cs#L6-L9

It would be great, if the UrhoSharp wrapper could decide at runtime which architecture of the native DLL to load.

**Comment by andrekoehler** [comment]
Here is a workaround for the case where you want to use UrhoSharp in a 32 bit only application:
Add the following lines in the project properties of your C# project under "Build Events" -> "Post-build event command line:"

> DEL "$(TargetDir)mono-urho.dll"
> RENAME "$(TargetDir)mono-urho_32bit.dll" "mono-urho.dll"

**Comment by migueldeicaza** [comment]
This is generally a problem with .NET that has a very inflexible system for loading libraries.

There are some proposals to look into this:

https://github.com/dotnet/coreclr/issues/12707

So at this point, I would just wait for this to be fixed at the core.

**Comment by EgorBo** [comment]
Usually on Windows developer solve this problem by ugly MSBuild hacks like "post-build tasks" 🙁

**Comment by andrekoehler** [comment]
You could also use a small hack like this one: https://stackoverflow.com/a/30646096/2955654

**Comment by EgorBo** [comment]
@andrekoehler perfect, thanks, it will also allow to switch between OpenGL and DirectX easily via ApplicationOptions

**Comment by dotMorten** [comment]
I have a much better way to handle this. The trick is to deploy both the x64 and x86 DLL in sub-folders, and make the two DLLs named the same. You then call SetDllDirectory based on the running architecture. You can see how I do that here:
https://github.com/dotMorten/IoTivityDotNet/blob/master/src/IotivityDotNet.Interop/Init.cs

Then in the nuget package you add a .targets file that xcopy deploys the correct one or both based on your anycpu/prefer32bit/x86/x64 build settings. You can see an example of my targets file here:
https://github.com/dotMorten/IoTivityDotNet/blob/master/src/IotivityDotNet.Interop/build/net452/dotMorten.IoTivity.Interop.targets

This approach allows users to create AnyCPU apps and run the same app on both x86 and x64 platforms.
