### ISSUE TITLE
Defining WINDOWS_D3D doesn't work out of the box, and crashes when you add as conditional to preprocessor

### ISSUE THREAD

**Issue by Alan-FGR** [xamarin/urho#293]
Disclaimer: I don't fully understand the projects hierarchy of UrhoSharp.
When I try to build UrhoSharp with WINDOWS_D3D defined, it errors because this doesn't account for it:
https://github.com/xamarin/urho/blob/2c09fdace48e747e044b000636c57e592cf35b6e/Bindings/Portable/UrhoPlatformInitializer.cs#L18-L28
Then I thought I should define both DESKTOP and WINDOWS_D3D, but then this fails:
https://github.com/xamarin/urho/blob/2c09fdace48e747e044b000636c57e592cf35b6e/Bindings/Portable/Consts.cs#L8-L16
So I reverted to just WINDOWS_D3D and changed the first line on the first excerpt to:
```c#
#if DESKTOP || WINDOWS_D3D
```
But strangely enough for some reason that causes the program to crash with no useful debugging data whatsoever, but it only crashes when ran from VS (both debug and release). I suspect it's something to do with that vshost attached to it, perhaps it's a bug in VS although I tested on different machines and different versions of 2017 (incl. latest).
The solution was to change the first line on the second link to:
```c#
#if DESKTOP && !WINDOWS_D3D
```
I have no idea why this latter works and the former doesn't.
I would also like to take this opportunity to say that I don't fully understand the project structure of UrhoSharp, I tried for example adding Urho.Desktop project in a new solution and reference to it in another project but I couldn't get that working, with errors regarding duplicated assembly.

**Comment by EgorBo** [comment]
Yeah, order of #if defs is wrong in Consts.cs
In order to try D3D renderer you need:
1) `make Windows_D3D11`
2) compile **UrhoSharp.WindowsD3D** project
3) Add WINDOWS_D3D symbol to Urho.Desktop (DESKTOP should also be defined)
4) Make sure your app uses mono-urho-d3d.dll lib

**Comment by EgorBo** [comment]
![image](https://user-images.githubusercontent.com/523221/36277710-b3599f78-12a2-11e8-8eb6-6632bc650ddd.png)
