### ISSUE TITLE
[Missing Binding] (TileMap2D) PositionToTileIndex

### ISSUE THREAD

**Issue by Scellow** [xamarin/urho#297]
Hello

``PositionToTileIndex`` is missing

https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Urho2D/TileMap2D.h#L69

https://github.com/xamarin/Urho3D/blob/c5a0ace541aa56a138994e09d4b53c13d22151a0/Source/Urho3D/Urho2D/TileMap2D.h#L69

Only  the opposite ``TileIndexToPosition`` is present
https://github.com/xamarin/urho/blob/master/Bindings/Portable/Generated/TileMap2D.cs#L190

**Comment by EgorBo** [comment]
Thanks, @Scellow 
Looks like Binder doesn't know what to do with int&.

**Comment by Scellow** [comment]
Thanks!
