### ISSUE TITLE
Nuget package 1.8.51 for SharpReality fails App Certification for Windows Store

### ISSUE THREAD

**Issue by davejmurphy** [xamarin/urho#299]
The error from the certification kit:
`API getenv in api-ms-win-crt-environment-l1-1-0.dll is not supported for this application type. mono-holourho.dll calls this API.`

The certification kit version: 10.0.16299.15
My OS version: 10.0.16299.0

This is a Release build for x86, and I'm compiling with .NET Native tool chain.

Note, the Nuget package 1.4.47 does pass store certification.

**Comment by EgorBo** [comment]
Fixed in master
