### ISSUE TITLE
Missing binding: RenderSurface::GetRenderBuffer/GetTarget

### ISSUE THREAD

**Issue by andrekoehler** [xamarin/urho#300]
I would like to use SkiaSharp to render with high performance into a RenderSurface. I see that the binding for RenderTarget offers "GetRenderTargetView" for Direct3D11 backends and "Surface" for Direct3D 9 backends (which are not supported by UrhoSharp as far as I know), but "GetRenderBuffer" or "GetTarget" are missing. These exist in the native Urho and are required to tell SkiaSharp where to render into.

**Comment by EgorBo** [comment]
Fixed in master, not sure why I marked those methods as OGL-only (probably they used to)
