### ISSUE TITLE
Switching between x64 and x86 on Windows (non UWP)

### ISSUE THREAD

**Issue by EgorBo** [xamarin/urho#307]
Unfortunately there is no really native solution to easily switch between the architectures on Windows (on all other platforms this problem is solved, for example, on macOS and iOS it's possible to use single "fat" libraries).

A possible solution is to use MSBuild hacks.

**Comment by dotMorten** [comment]
@EgorBo Do like I described here:
https://github.com/xamarin/urho/issues/291#issuecomment-369693197

I'd be open to adding this, if you reopen the issue

**Comment by EgorBo** [comment]
@dotMorten thanks! I'll take a look
