### ISSUE TITLE
UrhoSharp.Wpf version 1.8.91 is not exiting properly

### ISSUE THREAD

**Issue by Fido789** [xamarin/urho#312]
Application using UrhoSharp.Wpf version 1.8.91 is not exiting properly. After closing application's window there is some Urho's thread left running and Visual Studio goes to "This application is in break mode" mode. Application using UrhoSharp.Wpf version 1.8.71 is working fine.

Steps to reproduce:
Upgrade sample project Urho.Samples.WPF to version 1.8.91, run it and try to close the main window.

**Comment by EgorBo** [comment]
Fixed in master
