### ISSUE TITLE
UrhoSurface life

### ISSUE THREAD

**Issue by Zamir7** [xamarin/urho#318]
let there are two pages of ContentPage
             mainPage = new StartPage (); // simple form of xamarin
             urhoPage = new UrhoPage (); // form xamarin with UrhoSurface inside divide the screen in half
when navigating to pages
             MainPage = new NavigationPage (urhoPage); // or mainPage

The xamarin elements remain unchanged, but the UrhoSurface is destroyed and you have to recreate it.
Is it inevitable or how can you save the life of UrhoSurface during the transition?

**Comment by Meffi29a** [comment]
same issue in TabbedPage & MasterDetail but not on a CarouselPage. 
(off: do not try the Carousel bevor you can handle to overwrite the CarouselPageRenderer. The Swipe.Gesture kills the Tuchinput on the UrhoSUrface)

**Comment by Zamir7** [comment]
looked at it... is not so quickly killed, at least. Crashes after some touching in urhSurface
