### ISSUE TITLE
Does Urho support Metal in iOS

### ISSUE THREAD

**Issue by ywj7931** [xamarin/urho#343]
iOS is phasing out opengl starting from ios 12, I wonder if Urho supports Metal? If not, what is the plan considering iOS is phasing out opengl es?

**Comment by OmidID** [comment]
You can read more about this topic at urho website
https://discourse.urho3d.io/t/apple-deprecates-opengl-and-opencl/4288/16

**Comment by migueldeicaza** [comment]
This discussion really needs to take place on the urho forums, this is merely a binding to the underlying engine.
