### ISSUE TITLE
right to left languages

### ISSUE THREAD

**Issue by hassanrahimi** [xamarin/urho#350]
hi urho developers.
I have problems,urho don't support right to left languages like farsi and arbic. 
can you develop urho for support right to left languages? 
or learn to me how do might this.
I post here to show problem 
https://discourse.urho3d.io/t/use-right-to-left-languages/4546

**Comment by migueldeicaza** [comment]
This would need to be handled directly on the underlying Urho engine.

I am afraid that this is not exactly a simple problem, and would require Urho to implement proper text shaping, with somthing like Harfbuzz.
