### ISSUE TITLE
No Xamarin?

### ISSUE THREAD

**Issue by anonimo82** [xamarin/urho#358]
Can UrhoSharp be used with .NET, without Xamarin?

**Comment by OmidID** [comment]
It's working well with WPF and WinForms. By the way EgorBo finished .Net standard library too.
https://github.com/xamarin/urho/pull/353

**Comment by anonimo82** [comment]
Thanks. Just to be sure, do you thinkit would work with Limnor Studio? (http://www.limnor.com/)

**Comment by OmidID** [comment]
I have no idea what is that.

**Comment by anonimo82** [comment]
Nevermind. Where can I get it not for NuGet?

**Comment by hwd71** [comment]
Yeah, I couldn't integrate it with Lego either.. *sigh*.
Works with the windows console too (i.e. not WinForms).
"Urho nuget" works quite well in google.

**Comment by anonimo82** [comment]
Yes, but I don't need it from NuGet. Is there any way to download the dll file?

**Comment by anonimo82** [comment]
Nevermind, I downloaded the NuGet package from NuGet.org, renamed to .zip and extracted, works just fine with Limnor.
Thanks.
