### ISSUE TITLE
Latest nuget package + console app issue

### ISSUE THREAD

**Issue by laheller** [xamarin/urho#365]
Latest **v1.9.67** version of nuget package is not possible to add to a new empty **Windows Console** application.
Error message is following:

> Failed to add reference to 'mono-urho'.
> Please make sure that the file is accessible, and that it is a valid assembly or COM component.

**Comment by utekai** [comment]
Worked ok for me. I started a new console app and used nuget to add latest urhosharp. No problems. Using vs 2017.

**Comment by laheller** [comment]
> Worked ok for me. I started a new console app and used nuget to add latest urhosharp. No problems. Using vs 2017.

Interesting, because I am also using VS2017, the latest update of Community Edition and .NET 4.7.1.

**Comment by laheller** [comment]
Update: Solved. I had to clean nuget cache in VS.
