### ISSUE TITLE
Level Design Tool

### ISSUE THREAD

**Issue by furkansarihan** [xamarin/urho#370]
Can someone guide me to level design tool? So I will be able to export my scene from it.

I found a material graph editor with binary distribution and it comes with urho renderer and works. But I think it was not official and It is not enough for me.

I could not complete Urho3D installation from source code. Is there any other way to launch Urho3D?

Note: I don’t have complex scene, there is just some bunch of models and materials.

Thanks.

**Comment by barefists** [comment]
@furkansarihan I have a copy of the Urho3D Editor at this [link](https://drive.google.com/file/d/1AuoAnfXn1goq4TBkwRgVKlL3gGP2Saqp/view?usp=sharing). Alternatively, you could download the binary from the [Urho3D site](https://urho3d.github.io/releases/2017/08/19/urho3d-1.7-release.html), and look for Editor.bat there.

**Comment by furkansarihan** [comment]
Thank you, I downloaded yours.
