### ISSUE TITLE
ARCore and Xamarin Forms

### ISSUE THREAD

**Issue by deviloper** [xamarin/urho#384]
Hi, I'm trying to create a new Xamarin project for Android and iOS implementation of ARCore.
Visual Studio generated a .NET Standard project and two platform specific projects (Android and iOS).
How can I make a Urho Application in an independent library (.NET Standard 2) and then call and run it in a UrhoSurface component in my Xamarin Forms app?

Errors:
- Urho.Application is present both in UrhoSharp and UrhoSharp.Forms but UrhoSharp.ARCore depends by UrhoSharp, so the compiler gives an error.
- Xamarin Forms pages are in the .NET Standard project but Urhosharp.ARCore package needs a monodroid81 project.

Here follows my application stack:
![image](https://user-images.githubusercontent.com/5602328/59523385-6ed0d680-8ed1-11e9-812c-eb2a7cf5c11b.png)

**Comment by satputerohan** [comment]
Did you find a way to resolve this?

**Comment by deviloper** [comment]
I tried in many ways but finally i switched my develop environment to Unity3D which has full ARCore support despite it lacks UI controls.

I hope Xamarin will feature a new 3D engine based on Vulkan which would allow to develop 3D applications and games on Windows and mobile environments.
