### ISSUE TITLE
Unsubscribing from events currently unsuscribes all events

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/urho#39]
All events of a given type, because Urho does not have an API to remove just the susbscribed event/handler pair.

**Comment by EgorBo** [comment]
Was fixed here: https://github.com/xamarin/urho/blob/master/Bindings/Portable/Runtime/UrhoEventAdapter.cs#L46-L50 when user does let's say Input.KeyPressed -= OnKeyPressed. It won't necessarily call native Unsubscribe.
