### ISSUE TITLE
Problems trying to build on Visual Studio 19

### ISSUE THREAD

**Issue by redek91** [xamarin/urho#397]
Hi,

I am trying to build UrhoSharp from source for about 2 weeks without success.

When I follow the guide in the README.md
I can build  (with lots of workarounds) the Mac / Android parts.

But when i try to build on Windows i get always the same errors when I try to build Urhosharp:

`The specified language targets for monoandroid81 is missing. Ensure correct tooling is installed for 'monoandroid'. Missing: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.CSharp.targets'	UrhoSharp`

`The specified language targets for uap10.0.16299 is missing. Ensure correct tooling is installed for 'uap'. Missing: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\WindowsXaml\v16.0\Microsoft.Windows.UI.Xaml.CSharp.targets'`

I wonder if anyone is struggling with this project. Or do I miss something.

Can I build the project with Visual Studio 19 / Newest Visual Studio for Mac?

Can someone teach me the right way to compile this project?

Thank you

**Comment by Groovy1911** [comment]
Hi,
To download ARCore, you can follow this link:
https://mvnrepository.com/artifact/com.google.ar/core

Just remove the old one from Urho.droid.CoreAR and add the one as "LibProjectZip". 
Right click on the project then on ReBuild. You will have some errors from "Com.Google......"
You have to correct them then click right again on Urho.droid.CoreAR then Build (NOT REBUILD).
Once Urho.droid.CoreAR is correctly generated, you have to build Urho.Extensions.Droid.ARCore

**Comment by redek91** [comment]
Thank you. I managed to find the lib and to update it. Thank you
