### ISSUE TITLE
Support for "EngineParameters"

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/urho#44]
The engine parameters are the mechanism by which the engine is configured at startup, we need to bind and surface these parameters to managed code.   

Application::Setup allows the engine to be tuned here:

```
// Modify engine startup parameters
engineParameters_["WindowTitle"] = GetTypeName();
engineParameters_["LogName"]     = GetSubsystem<FileSystem>()->GetAppPreferencesDir("urho3d", "logs") + GetTypeName() + ".log";
engineParameters_["FullScreen"]  = false;
engineParameters_["Headless"]    = false;
```

**Comment by EgorBo** [comment]
Closed as most of the arguments are surfaced in ApplicationOptions.
