### ISSUE TITLE
Optimization: delay subscription of SceneUpdate/Update

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/urho#59]
We should probably only subscribe to those events if:

(a) the user has overwritten the SceneUpdate/OnUpdate methods
(b) on the event handlers, we can detect if we are not subscribed, and if not, configure the subcription at that point.

**Comment by EgorBo** [comment]
In all components user has to enabled flags like ReceiveUpdate = true in order to receive updates in "override OnUpdate" so this solves the possible overhead.
