### ISSUE TITLE
Surface Scene.Save, Scene.Load

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/urho#62]
These take a Serializer, and that is why it does not work.   Because serializer is a bit of a strange class, that is implemented by File, MemoryBuffer and VectorBuffer.

We should figure out if we can either surface a Save(File), Save(MemoryBuffer), Save(VectorBuffer) as alternatives to doing Save(Serializer) which is just not easy to bind.

**Comment by EgorBo** [comment]
Fixed a long time ago (except VectorBuffer, don't think we need it). File, MemoryBuffer (MemoryStream\byte[]) are supported.
