### ISSUE TITLE
x86 support for Windows

### ISSUE THREAD

**Issue by EgorBo** [xamarin/urho#70]
Unlike OSX, windows supports x64 only now and since the Console Applications with AnyCPU prefer x86 by default even on Windows x64 - it would be nice to have x86 support on windows too.
It's easy to add, the only problem is nuget - it's a bit tricky.

**Comment by MihaMarkic** [comment]
Why? Just set it to x64 and you don't need x86. I don't think there are many x86 CPUs out there.

**Comment by EgorBo** [comment]
@MihaMarkic what if your game uses some old/legacy 32bit only dependency? :) btw, ConsoleApplications by default uses x86 even on 64bit machines.

**Comment by EgorBo** [comment]
x86 support is added.
