### ISSUE TITLE
SubscribeToReleased not working on ios

### ISSUE THREAD

**Issue by jasallen** [xamarin/urho#86]
This can be seen on Samples:  HelloGui, SoundEffects, Chat.

Works on ios physical device.  Works on UrhoSharp Android (in simulator and device).  Works on non-sharp Urho3d iOS (in simulator and device).

SubscribeToSliderChanged may also have issue.

**Comment by EgorBo** [comment]
@jasallen so it's not working on iOS simulator only? (title says just on iOS)

**Comment by Therzok** [comment]
I don't have a device to test, but an ios sim definitely ain't working.

**Comment by EgorBo** [comment]
Fixed with Urho3D update
