### ISSUE TITLE
Actions for UI elements

### ISSUE THREAD

**Issue by Therzok** [xamarin/urho#87]
It would be nice to be able to attach actions running from UI elements such as Texts.

`text.RunActionsAsync(new CallFunc(() => text.Value = $"Text {x}"), new DelayTime(1));`

Makes for a such nicer approach than shoving them in the update override or using a fake node.

**Comment by Zamir7** [comment]
or await window.RunActionsAsync(new Parallel( 
                                  new EaseSineOut(new FadeOut(duration: 0.17f)), 
                                  new EaseSineOut(new ScaleTo(duration: 0.14f, scale: zoom / 2f))));

Connect an Action to UI it's too energy-consuming?

**Comment by EgorBo** [comment]
@Zamir7  Unfortunately, UI elements are not components and are not part of Scene hierarchy (Actions work only for nodes). So yes it will be quite time consuming to implement.
