### ISSUE TITLE
Installing UrhoSharp into PCL via nuget

### ISSUE THREAD

**Issue by Matt-17** [xamarin/urho#89]
On xamarin.com it says I can install Urho via nuget. Also there it says, I can use it in a PCL. But then I get the error: ".NETportable, Version=4.5, Profile=Profile111 is not compatible". Is there any way I can use nuget?

**Comment by Therzok** [comment]
If I'm not mistaken Profile111 has Windows Phone support, and UrhoSharp does not support Windows Phone.

**Comment by Therzok** [comment]
Based on [this link](http://urho3d.github.io/documentation/HEAD/_building.html) Urho itself does not support Windows Phone. In [this thread](http://urho3d.prophpbb.com/topic398-10.html) it is mentioned that preliminary support to make it happen has been written, but there's no target for Windows Phone to build the native libraries.

**Comment by Matt-17** [comment]
Thanks. Now I removed everything that has windows in it (profile 24) and it's also not working :/

**Comment by Therzok** [comment]
Heya! You can use Profile 7 (windows 8, mac, windows store apps, xamarin ios and xamarin android). Possibly you can't use profile 24 because it uses .NET 4.0, and UrhoSharp is .NET 4.5.

**Comment by Therzok** [comment]
Oh, and, Profile 24 also uses Silverlight, which is not a supported target.

**Comment by migueldeicaza** [comment]
So it seems like this is not a bug then?

Perhaps we need to explain this in the documentation?

**Comment by Therzok** [comment]
Definitely not a bug nuget/deployment. Just not a profile that our PCL supports.

**Comment by EgorBo** [comment]
We use Profile7 so the package expects your PCL to be the same. (Profile7 is set by default when you create an empty PCL by Visual Studio).
