### ISSUE TITLE
Missing Universal Windows Platform (UWP) support

### ISSUE THREAD

**Issue by RecursiveCall** [xamarin/urho#90]
Seems that Urho can only be used for an iOS, Android or a Windows Desktop project. UWP support is missing.

**Comment by JimSEOW** [comment]
I have seen that the Master Branch has incorporated the UWP branch
https://github.com/xamarin/urho/tree/uwp

When can we get NuGet UrhoSharp that reflects the UWP branch? Thanks

**Comment by EgorBo** [comment]
@JimSEOW the latest "prerelease" nuget update contains UWP support

**Comment by JimSEOW** [comment]
Thanks! Great news!  How about UrhoSharp.Forms for UWP?

In https://github.com/xamarin/urho/tree/master/Nuget/UWP
There is on UrhoSharp.targets, no  UrhoSharp.Forms.targets 

Is there a way that I can compile based on UrhoSharp 1.0.454-beta to get UrhoSharp.Forms that are compatible for UWP using Xamarin.Forms?

Great Jobs!

**Comment by JimSEOW** [comment]
Great Jobs!

**Comment by thargy** [comment]
I still can't get this working with the latest 1.0.577 NuGet, even with a blank project, a call to the `UrhoSurface.Run<T>("myassets.pak");` completes and the app continues to display a blue screen.  (Note See also [Issue 14 on Urho Samples](https://github.com/xamarin/urho-samples/issues/14)

**Comment by JimSEOW** [comment]
Can you get this simple test UWP UrhoSharp to work?
https://github.com/JimSEOW/UrhoSharpTest

**Comment by EgorBo** [comment]
@thargy @JimSEOW make sure pak file has "Content" build action and x86 arch is selected.
@JimSEOW in your sample pak file is not a "Content" (it's "None").

**Comment by thargy** [comment]
I had the content setting, but was trying to run as x64.  Thanks.

**Comment by JimSEOW** [comment]
thanks

**Comment by JimSEOW** [comment]
I suggest we close this issue. @EgorBo has implemented almost all essential UWP support.
