### ISSUE TITLE
PhysicsRaycastResult struct missing field

### ISSUE THREAD

**Issue by mhutch** [xamarin/urho#95]
The PhysicsRaycastResult struct is missing the HitFraction field in the 360 release. This causes crashes.

**Comment by EgorBo** [comment]
@mhutch thank you for noticing it. The sizeof of the struct remains the same so that's why it passed assert.h https://github.com/xamarin/urho/blob/5c463c79fdb8a9964822176085636650cf533453/Bindings/Native/asserts.h#L286
